#!/usr/bin/env python3
"""Post one-click GitHub suggestion comments for advisory Vale findings.

Reads `.style-suggestions.json` — written by the editorial pass, which
converts the advisory (non-blocker) style findings whose rewrite is a clear
improvement into concrete replacements (see the "Style suggestions" section of
the review prompt in claude-code-review.yml). Validates each entry against
the checked-out PR head and the PR diff, then posts ONE pull-request review
(event=COMMENT) whose inline comments each carry a ```suggestion block the
author can apply with a click ("Add suggestion to batch" applies all in one
commit).

Contract:
- Advisory tier only. Blocker findings render in the pinned review's 🚨
  bucket and are never suggestions.
- Flag-only stays true in spirit: nothing is committed here; the author
  applies or dismisses each suggestion. The meaning-preservation judgment
  the deterministic-fix gate requires (see vale-deterministic-fixes.yaml)
  is exercised twice — once by the editorial pass authoring the rewrite,
  once by the author clicking.
- The collapsed `#### Style suggestions` block in the pinned review remains
  the complete record; a suggested finding is NOT removed from it.
- Idempotent per run: prior suggestion comments (MARKER match) are deleted
  before posting — same delete-and-repost semantics as TRIAGE_PROSE.
- Never fails the workflow: any validation or API problem logs a warning
  and exits 0. Entries that fail validation are dropped individually.

Per-entry validation (anti-hallucination — the model wrote the JSON):
- `file`, `line`, `original`, `replacement` present; replacement differs.
- `line` is a PR-ADDED line (reuses added_lines_per_file from
  vale-findings-filter.py over the PR patch) — GitHub suggestions can only
  anchor to diff lines, and advisory findings are diff-intersected upstream,
  so a miss here means the entry drifted.
- `original` occurs verbatim on that exact line of the checked-out file;
  the suggestion body is the full line with the first occurrence swapped.
- Capped at MAX_SUGGESTIONS total; excess entries are dropped with a log.

Input schema (.style-suggestions.json):
    [
      {"file": "content/docs/foo.md", "line": 42,
       "original": "utilize", "replacement": "use",
       "category": "wordiness", "note": "shorter and identical in meaning"},
      ...
    ]

Usage:
    post-style-suggestions.py --pr N [--repo owner/repo]
        [--in .style-suggestions.json] [--patch-file diff.patch] [--dry-run]

--patch-file reads the PR diff from a file instead of `gh pr diff` (tests).
--dry-run validates and prints the review payload without calling gh.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Reuse the diff parser that already defines "PR-added line" for Vale
# findings, so both ends of the pipeline agree on anchorability.
_spec = importlib.util.spec_from_file_location(
    "vale_findings_filter", HERE / "vale-findings-filter.py")
_vff = importlib.util.module_from_spec(_spec)
sys.modules["vale_findings_filter"] = _vff
_spec.loader.exec_module(_vff)  # type: ignore[union-attr]

MARKER = "<!-- CLAUDE_STYLE_SUGGESTION -->"
MAX_SUGGESTIONS = 10
# Resolve the repo from the environment, never a hardcoded upstream name: the
# same script runs on the CamSoper/pulumi.docs test fork, where a hardcoded
# `pulumi/docs` makes every write 403 ("Resource not accessible by
# integration") because the fork's GITHUB_TOKEN is scoped to the fork. The
# workflow also passes --repo explicitly; this default just keeps a bare
# invocation honest.
DEFAULT_REPO = os.environ.get("GITHUB_REPOSITORY") or "pulumi/docs"

REVIEW_BODY = (
    f"{MARKER}\n"
    "🧹 **One-click style suggestions** — optional rewrites for advisory style "
    "findings from the pre-merge review. Apply the ones that read better "
    "(\"Add suggestion to batch\" commits them all at once); dismiss the rest. "
    "None of these block the PR.\n\n"
    "---\n"
    "_Generated by [Claude Code](https://claude.ai/code)_"
)


def validate_entries(
    entries: list,
    added_lines: dict[str, set[int]],
    repo_root: Path,
) -> tuple[list[dict], list[str]]:
    """Return (valid suggestion dicts, human-readable drop reasons).

    Valid dicts gain a `new_line` key: the full replacement line for the
    ```suggestion block.
    """
    valid: list[dict] = []
    dropped: list[str] = []
    seen: set[tuple[str, int]] = set()
    file_cache: dict[str, list[str] | None] = {}

    if not isinstance(entries, list):
        return [], ["input is not a JSON array"]

    for i, e in enumerate(entries):
        tag = f"entry {i}"
        if not isinstance(e, dict):
            dropped.append(f"{tag}: not an object")
            continue
        fname = e.get("file")
        line = e.get("line")
        original = e.get("original")
        replacement = e.get("replacement")
        if not (isinstance(fname, str) and isinstance(line, int)
                and isinstance(original, str) and isinstance(replacement, str)):
            dropped.append(f"{tag}: missing/mistyped file, line, original, or replacement")
            continue
        tag = f"{fname}:{line}"
        if not original or original == replacement:
            dropped.append(f"{tag}: empty original or no-op replacement")
            continue
        if (fname, line) in seen:
            dropped.append(f"{tag}: duplicate anchor")
            continue
        if line not in added_lines.get(fname, set()):
            dropped.append(f"{tag}: not a PR-added line (suggestion can't anchor)")
            continue
        if fname not in file_cache:
            try:
                file_cache[fname] = (repo_root / fname).read_text(
                    encoding="utf-8").splitlines()
            except (OSError, UnicodeDecodeError):
                file_cache[fname] = None
        lines = file_cache[fname]
        if lines is None:
            dropped.append(f"{tag}: file unreadable in checkout")
            continue
        if line < 1 or line > len(lines):
            dropped.append(f"{tag}: line out of range ({len(lines)} lines)")
            continue
        content = lines[line - 1]
        if original not in content:
            dropped.append(f"{tag}: original text not found on that line")
            continue
        new_line = content.replace(original, replacement, 1)
        if new_line == content:
            dropped.append(f"{tag}: replacement produced no change")
            continue
        seen.add((fname, line))
        valid.append({**e, "new_line": new_line})

    if len(valid) > MAX_SUGGESTIONS:
        for e in valid[MAX_SUGGESTIONS:]:
            dropped.append(f"{e['file']}:{e['line']}: over the {MAX_SUGGESTIONS}-suggestion cap")
        valid = valid[:MAX_SUGGESTIONS]
    return valid, dropped


def comment_body(e: dict) -> str:
    cat = str(e.get("category") or "style")
    note = str(e.get("note") or "").strip()
    note_part = f" — {note}" if note else ""
    return (
        f"{MARKER}\n"
        f"[style] _{cat}_{note_part}\n"
        "```suggestion\n"
        f"{e['new_line']}\n"
        "```"
    )


def build_review_payload(valid: list[dict]) -> dict:
    return {
        "event": "COMMENT",
        "body": REVIEW_BODY,
        "comments": [
            {"path": e["file"], "line": e["line"], "side": "RIGHT",
             "body": comment_body(e)}
            for e in valid
        ],
    }


def gh_api(args: list[str], input_json: dict | None = None) -> subprocess.CompletedProcess:
    cmd = ["gh", "api"] + args
    return subprocess.run(
        cmd,
        input=json.dumps(input_json) if input_json is not None else None,
        capture_output=True, text=True,
    )


def delete_prior_suggestions(repo: str, pr: str) -> None:
    """Delete review comments from previous runs (MARKER match)."""
    proc = gh_api([
        f"repos/{repo}/pulls/{pr}/comments", "--paginate",
        "--jq", f'.[] | select(.body | startswith("{MARKER}")) | .id',
    ])
    if proc.returncode != 0:
        print(f"post-style-suggestions: could not list prior comments: {proc.stderr.strip()}",
              file=sys.stderr)
        return
    for cid in proc.stdout.split():
        d = gh_api(["-X", "DELETE", f"repos/{repo}/pulls/comments/{cid}"])
        if d.returncode != 0:
            print(f"post-style-suggestions: could not delete comment {cid}: {d.stderr.strip()}",
                  file=sys.stderr)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pr", required=True)
    ap.add_argument("--repo", default=DEFAULT_REPO)
    ap.add_argument("--in", dest="infile", default=".style-suggestions.json")
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--patch-file", help="Read the PR diff from a file instead of `gh pr diff` (tests).")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    path = Path(args.infile)
    if not path.is_file():
        print("post-style-suggestions: no suggestions file; nothing to post.", file=sys.stderr)
        return 0
    try:
        entries = json.loads(path.read_text(encoding="utf-8") or "[]")
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        print(f"post-style-suggestions: unreadable {path}: {exc}", file=sys.stderr)
        return 0

    if args.patch_file:
        patch = Path(args.patch_file).read_text(encoding="utf-8")
    else:
        proc = subprocess.run(
            ["gh", "pr", "diff", args.pr, "--repo", args.repo, "--patch"],
            capture_output=True, text=True)
        if proc.returncode != 0:
            print(f"post-style-suggestions: gh pr diff failed: {proc.stderr.strip()}",
                  file=sys.stderr)
            return 0
        patch = proc.stdout
    added = _vff.added_lines_per_file(patch)

    valid, dropped = validate_entries(entries, added, Path(args.repo_root))
    for reason in dropped:
        print(f"post-style-suggestions: dropped {reason}", file=sys.stderr)
    print(f"post-style-suggestions: {len(valid)} valid suggestion(s), {len(dropped)} dropped.",
          file=sys.stderr)

    payload = build_review_payload(valid)
    if args.dry_run:
        print(json.dumps(payload, indent=2))
        return 0

    # Even with zero valid suggestions, clear stale ones from a prior run —
    # a re-review that fixed everything should leave no orphaned comments.
    delete_prior_suggestions(args.repo, args.pr)
    if not valid:
        return 0

    proc = gh_api(
        ["-X", "POST", f"repos/{args.repo}/pulls/{args.pr}/reviews", "--input", "-"],
        input_json=payload,
    )
    if proc.returncode != 0:
        print(f"post-style-suggestions: review POST failed: {proc.stderr.strip()}",
              file=sys.stderr)
        return 0
    print(f"post-style-suggestions: posted {len(valid)} suggestion(s).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
