# -------------------------------------
# Command Line Menu
# -------------------------------------

[[reference]]
    name = "cancel"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_cancel/"
    weight = 1

[[reference]]
    name = "config"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_config/"
    weight = 2

[[reference]]
    name = "destroy"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_destroy/"
    weight = 3

[[reference]]
    name = "history"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_history/"
    weight = 4

[[reference]]
    name = "login"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_login/"
    weight = 5

[[reference]]
    name = "logout"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_logout/"
    weight = 6

[[reference]]
    name = "logs"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_logs/"
    weight = 7

[[reference]]
    name = "new"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_new/"
    weight = 8

[[reference]]
    name = "plugin"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_plugin/"
    weight = 9

[[reference]]
    name = "preview"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_preview/"
    weight = 10

[[reference]]
    name = "refresh"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_refresh/"
    weight = 11

[[reference]]
    name = "stack"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_stack/"
    weight = 12

[[reference]]
    name = "state"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_state/"
    weight = 13

[[reference]]
    name = "up"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_up/"
    weight = 14

[[reference]]
    name = "version"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_version/"
    weight = 15

[[reference]]
    name = "whoami"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_whoami/"
    weight = 16


# -------------------------------------
# API Reference Menu
# -------------------------------------

[[reference]]
    parent = "node"
    identifier = "node-pulumi"
    name = "pulumi"
    url = "/docs/reference/pkg/nodejs/pulumi/pulumi/"
    weight = 1

[[reference]]
    parent = "node"
    name = "aws"
    url = "/docs/reference/pkg/nodejs/pulumi/aws/"

[[reference]]
    parent = "node"
    name = "awsx"
    url = "/docs/reference/pkg/nodejs/pulumi/awsx/"

[[reference]]
    parent = "node"
    name = "azure"
    url = "/docs/reference/pkg/nodejs/pulumi/azure/"

[[reference]]
    parent = "node"
    name = "azuread"
    url = "/docs/reference/pkg/nodejs/pulumi/azuread/"

[[reference]]
    parent = "node"
    name = "cloud"
    url = "/docs/reference/pkg/nodejs/pulumi/cloud/"

# Note: We deliberately aren't including the @pulumi/cloud-aws and @pulumi/cloud-azure
# packages in the docs listing as they are implementation details of @pulumi/cloud.

[[reference]]
    parent = "node"
    name = "cloudflare"
    url = "/docs/reference/pkg/nodejs/pulumi/cloudflare/"

[[reference]]
    parent = "node"
    name = "datadog"
    url = "/docs/reference/pkg/nodejs/pulumi/datadog/"

[[reference]]
    parent = "node"
    name = "digitalocean"
    url = "/docs/reference/pkg/nodejs/pulumi/digitalocean/"

[[reference]]
    parent = "node"
    name = "dnsimple"
    url = "/docs/reference/pkg/nodejs/pulumi/dnsimple/"

[[reference]]
    parent = "node"
    name = "docker"
    url = "/docs/reference/pkg/nodejs/pulumi/docker/"

[[reference]]
    parent = "node"
    name = "eks"
    url = "/docs/reference/pkg/nodejs/pulumi/eks/"

[[reference]]
    parent = "node"
    name = "f5bigip"
    url = "/docs/reference/pkg/nodejs/pulumi/f5bigip/"

[[reference]]
    parent = "node"
    name = "gcp"
    url = "/docs/reference/pkg/nodejs/pulumi/gcp/"

[[reference]]
    parent = "node"
    name = "gitlab"
    url = "/docs/reference/pkg/nodejs/pulumi/gitlab/"

[[reference]]
    parent = "node"
    name = "kubernetes"
    url = "/docs/reference/pkg/nodejs/pulumi/kubernetes/"

[[reference]]
    parent = "node"
    name = "linode"
    url = "/docs/reference/pkg/nodejs/pulumi/linode/"

[[reference]]
    parent = "node"
    name = "mysql"
    url = "/docs/reference/pkg/nodejs/pulumi/mysql/"

[[reference]]
    parent = "node"
    name = "newrelic"
    url = "/docs/reference/pkg/nodejs/pulumi/newrelic/"

[[reference]]
    parent = "node"
    name = "openstack"
    url = "/docs/reference/pkg/nodejs/pulumi/openstack/"

[[reference]]
    parent = "node"
    name = "packet"
    url = "/docs/reference/pkg/nodejs/pulumi/packet/"

[[reference]]
    parent = "node"
    name = "postgresql"
    url = "/docs/reference/pkg/nodejs/pulumi/postgresql/"

[[reference]]
    parent = "node"
    name = "random"
    url = "/docs/reference/pkg/nodejs/pulumi/random/"

[[reference]]
    parent = "node"
    name = "terraform"
    url = "/docs/reference/pkg/nodejs/pulumi/terraform/"

[[reference]]
    parent = "node"
    name = "tls"
    url = "/docs/reference/pkg/nodejs/pulumi/tls/"

[[reference]]
    parent = "node"
    name = "vsphere"
    url = "/docs/reference/pkg/nodejs/pulumi/vsphere/"

[[reference]]
    parent = "python"
    identifier = "python-pulumi"
    name = "pulumi"
    url = "/docs/reference/pkg/python/pulumi/"
    weight = 1

[[reference]]
    parent = "python"
    name = "pulumi_aws"
    url = "/docs/reference/pkg/python/pulumi_aws/"

[[reference]]
    parent = "python"
    name = "pulumi_azure"
    url = "/docs/reference/pkg/python/pulumi_azure/"

[[reference]]
    parent = "python"
    name = "pulumi_azuread"
    url = "/docs/reference/pkg/python/pulumi_azuread/"

[[reference]]
    parent = "python"
    name = "pulumi_cloudflare"
    url = "/docs/reference/pkg/python/pulumi_cloudflare/"

[[reference]]
    parent = "python"
    name = "pulumi_datadog"
    url = "/docs/reference/pkg/python/pulumi_datadog/"

[[reference]]
    parent = "python"
    name = "pulumi_digitalocean"
    url = "/docs/reference/pkg/python/pulumi_digitalocean/"

[[reference]]
    parent = "python"
    name = "pulumi_dnsimple"
    url = "/docs/reference/pkg/python/pulumi_dnsimple/"

[[reference]]
    parent = "python"
    name = "pulumi_f5bigip"
    url = "/docs/reference/pkg/python/pulumi_f5bigip/"

[[reference]]
    parent = "python"
    name = "pulumi_gcp"
    url = "/docs/reference/pkg/python/pulumi_gcp/"

[[reference]]
    parent = "python"
    name = "pulumi_gitlab"
    url = "/docs/reference/pkg/python/pulumi_gitlab/"

[[reference]]
    parent = "python"
    name = "pulumi_kubernetes"
    url = "/docs/reference/pkg/python/pulumi_kubernetes/"

[[reference]]
    parent = "python"
    name = "pulumi_linode"
    url = "/docs/reference/pkg/python/pulumi_linode/"

[[reference]]
    parent = "python"
    name = "pulumi_mysql"
    url = "/docs/reference/pkg/python/pulumi_mysql/"

[[reference]]
    parent = "python"
    name = "pulumi_newrelic"
    url = "/docs/reference/pkg/python/pulumi_newrelic/"

[[reference]]
    parent = "python"
    name = "pulumi_openstack"
    url = "/docs/reference/pkg/python/pulumi_openstack/"

[[reference]]
    parent = "python"
    name = "pulumi_postgresql"
    url = "/docs/reference/pkg/python/pulumi_postgresql/"

[[reference]]
    parent = "python"
    name = "pulumi_random"
    url = "/docs/reference/pkg/python/pulumi_random/"

[[reference]]
    parent = "python"
    name = "pulumi_tls"
    url = "/docs/reference/pkg/python/pulumi_tls/"

[[reference]]
    parent = "python"
    name = "pulumi_vsphere"
    url = "/docs/reference/pkg/python/pulumi_vsphere/"
