# -------------------------------------
# Command Line Menu
# -------------------------------------

[[reference]]
    name = "cancel"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_cancel/"
    weight = 1

[[reference]]
    name = "config"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_config/"
    weight = 2

[[reference]]
    name = "destroy"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_destroy/"
    weight = 3

[[reference]]
    name = "history"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_history/"
    weight = 4

[[reference]]
    name = "login"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_login/"
    weight = 5

[[reference]]
    name = "logout"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_logout/"
    weight = 6

[[reference]]
    name = "logs"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_logs/"
    weight = 7

[[reference]]
    name = "new"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_new/"
    weight = 8

[[reference]]
    name = "plugin"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_plugin/"
    weight = 9

[[reference]]
    name = "preview"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_preview/"
    weight = 10

[[reference]]
    name = "refresh"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_refresh/"
    weight = 11

[[reference]]
    name = "stack"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_stack/"
    weight = 12

[[reference]]
    name = "state"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_state/"
    weight = 13

[[reference]]
    name = "up"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_up/"
    weight = 14

[[reference]]
    name = "version"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_version/"
    weight = 15

[[reference]]
    name = "whoami"
    parent = "cli"
    url = "/docs/reference/cli/pulumi_whoami/"
    weight = 16
