#!/usr/bin/env python3
"""The act primitive for /pr-review: plan → preview → execute, batch-capable.

    act.py --in .pr-review-queue.json --stamp 21550,21577 --route 21431:@cnunciato \\
           --unblock 21525 --plan-out .pr-review-plan.json          # plan + preview
    act.py --execute .pr-review-plan.json [--dry-run]                # run it

Actions (each a `Step`; every one goes through the same preview/confirm,
comment templates and attribution footer):

  --stamp N,N        approve, then squash-merge, after a per-PR preflight run
                     immediately before each merge: head SHA unchanged since
                     the plan, mergeable_state in {clean, blocked}, checks
                     green, no changes-requested review. master moves during
                     a batch; the preflight is what makes a batch safe. Bot
                     PRs merge; a human-authored PR is approved only unless
                     --merge-humans (authors merge their own PRs).
  --route N:@user|team   request review and post the row's defects (reason
                     codes + judgments) as one comment.
  --request-changes N    post a CHANGES_REQUESTED review built from the row's
                     judgments (one line-anchored item each, no filler) and
                     apply `needs-author-response`. The author-facing verb the
                     old menus had; the approver's way to say "your turn".
  --chain C1         start a collision cluster's chain: stamp the first PR in
                     its merge order (--force when it is a judge row), then
                     merge base into the next one so the following run finds
                     it green instead of dirty. One link per run; each link
                     waits on CI.
  --unblock N        merge the base branch into the head as a merge commit
                     (never rebase, never force-push). Only conflict-free
                     merges are pushed; anything else is aborted and reported.
  --fix N            apply the drafted description correction and any
                     one-click ✏️ suggestions, commit, push.
  --close N --superseded-by M   close N with a cross-link comment on both.
  --refresh N        post `@claude <reason> #update-review`.
  --rerun N          post `@claude <reason> #new-review` (fresh review from scratch).
  --render N         screenshot the preview pages (screenshot.mjs + Playwright).
  --deploy N         dispatch testing-build-and-deploy.yml at the head branch.

Bot branches: dependabot and the generated-docs regens (pulumi-bot +
`automation/merge`) are never pushed to; workprentice and content-review/*
branches may be, as merge commits. Every comment act.py posts carries the
Claude Code attribution footer except the approval review body, which
follows references/message-templates.md (one line, no process narration).

GitHub goes through gh_client.GhClient (gh / REST token / snapshot); git
through the small `Git` wrapper here so tests stub both. Deterministic, no
model calls — the drafted description fix and the judgments come in on the
queue, written by the judge step before this runs.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent
sys.path.insert(0, str(_HERE))
import collect  # noqa: E402
import gh_client  # noqa: E402
from gh_client import GhClient, GhError, norm_login  # noqa: E402

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
STAMP_STATES = ("clean", "blocked")
DEPLOY_WORKFLOW = "testing-build-and-deploy.yml"
SHOTS_DIR = _REPO_ROOT / ".pr-review-shots"
PLAN_SCHEMA = 1
COMMIT_TRAILER_ENV = "PR_REVIEW_COMMIT_TRAILER"  # e.g. "Co-Authored-By: …"; appended to commits act.py makes


class ActError(Exception):
    pass


@dataclass
class Step:
    kind: str
    pr: int
    args: dict = field(default_factory=dict)
    expect_head: str = ""
    title: str = ""
    author: str = ""
    author_type: str = "bot"
    branch: str = ""
    verdict: str = ""
    note: str = ""


@dataclass
class Plan:
    schema: int
    repo: str
    created_at: str
    options: dict
    steps: list[Step]

    def to_json(self) -> dict:
        return {"schema": self.schema, "repo": self.repo, "created_at": self.created_at,
                "options": self.options, "steps": [asdict(s) for s in self.steps]}

    @classmethod
    def from_json(cls, d: dict) -> "Plan":
        return cls(d["schema"], d["repo"], d["created_at"], d.get("options") or {}, [Step(**s) for s in d["steps"]])


@dataclass
class Result:
    step: Step
    ok: bool
    message: str
    writes: list[dict] = field(default_factory=list)


# ---- policy -----------------------------------------------------------------


def push_allowed(pr: dict) -> tuple[bool, str]:
    """Which bot branches may be pushed to (see references/action-menus.md)."""
    login = norm_login((pr.get("author") or {}).get("login"))
    labels = set(pr.get("labels") or [])
    if login.startswith("dependabot"):
        return False, "dependabot PRs are regenerated, never edited"
    if login == "pulumi-bot" and "automation/merge" in labels:
        return False, "generated-docs regens are regenerated, never edited"
    if (pr.get("head") or {}).get("is_fork"):
        return False, "fork head: no push access"
    return True, "merge commits only, never rebase or force-push"


def approval_body(author_type: str, trust: str = "high", note: str = "") -> str:
    """references/message-templates.md: bot 1 sentence, internal ≤2,
    external ≤3 (welcome only for a first-timer). No footer, no process."""
    if author_type == "bot":
        body = "Approved."
    elif author_type == "external":
        body = "Thanks! LGTM." + (" Welcome to Pulumi. 🎉" if trust == "low" else " 🎉")
    else:
        body = "LGTM."
    if note:
        body += " " + note.strip()
    return body


def with_footer(body: str) -> str:
    return body.rstrip() + FOOTER


# ---- planning ------------------------------------------------------------------


def _split_numbers(spec: str | None) -> list[int]:
    if not spec:
        return []
    out = []
    for part in re.split(r"[,\s]+", spec.strip()):
        if part:
            out.append(int(part.lstrip("#")))
    return out


def plan(queue: dict, args: argparse.Namespace) -> Plan:
    by = {p["number"]: p for p in queue.get("prs") or []}

    def pr_of(n: int) -> dict:
        if n not in by:
            raise ActError(f"#{n} is not in the queue; re-run collect (drafts and filtered rows are never acted on)")
        return by[n]

    def step(kind: str, n: int, **kw) -> Step:
        pr = pr_of(n)
        return Step(kind, n, kw, expect_head=(pr.get("head") or {}).get("sha") or "", title=pr.get("title") or "",
                    author=(pr.get("author") or {}).get("login") or "", author_type=(pr.get("author") or {}).get("type") or "bot",
                    branch=(pr.get("head") or {}).get("ref") or "", verdict=pr.get("verdict") or "")

    steps: list[Step] = []
    for n in _split_numbers(args.stamp):
        pr = pr_of(n)
        if pr.get("verdict") != "stamp" and not args.force:
            raise ActError(f"#{n} is {pr.get('verdict')}, not stamp — pass --force to approve as-is ({', '.join(pr.get('reasons') or [])})")
        if pr.get("verdict") == "blocked":
            raise ActError(f"#{n} is blocked ({', '.join(pr.get('blockers') or [])}); unblock it first")
        merge = not args.no_merge and (pr.get("author", {}).get("type") == "bot" or args.merge_humans)
        s = step("stamp", n, merge=merge, note=args.approve_note or "")
        s.note = "" if merge else "approve only (human author; --merge-humans to merge)"
        steps.append(s)
    for spec in args.route or []:
        n, _, target = spec.partition(":")
        if not target:
            pr = pr_of(int(n))
            act = next((a for a in pr.get("actions") or [] if a["id"] == "route"), None)
            target = act["cmd"].split(":", 1)[1] if act else ""
        if not target:
            raise ActError(f"--route {spec}: no target and the row has no route action")
        steps.append(step("route", int(n), target=target))
    for n in args.request_changes or []:
        pr = pr_of(n)
        if not (pr.get("judgments") or open_items(pr)):
            raise ActError(f"--request-changes {n}: nothing to send back — no judgments and no open findings on the row")
        steps.append(step("request-changes", n, note=args.reason or ""))
    for cid in args.chain or []:
        c = next((c for c in queue.get("clusters") or [] if c["id"] == cid), None)
        if not c:
            raise ActError(f"--chain {cid}: no such cluster in the queue")
        r = c.get("recommendation") or {}
        if r.get("kind") != "chain":
            raise ActError(f"--chain {cid}: the cluster's recommendation is {r.get('kind') or 'none'}, not chain ({r.get('say', '')})")
        first, nxt = r["first"], r.get("next")
        pr = pr_of(first)
        merge = not args.no_merge and (pr.get("author", {}).get("type") == "bot" or args.merge_humans)
        st = step("stamp", first, merge=merge, note=args.approve_note or "", chain=cid)
        st.note = "" if merge else "approve only (human author; --merge-humans to merge)"
        steps.append(st)
        if nxt and merge:
            ok, why = push_allowed(pr_of(nxt))
            if not ok:
                raise ActError(f"--chain {cid}: next link #{nxt} can't be pushed to: {why}")
            steps.append(step("unblock", nxt, chain=cid))
    for n in args.unblock or []:
        pr = pr_of(n)
        ok, why = push_allowed(pr)
        if not ok:
            raise ActError(f"--unblock {n}: {why}")
        steps.append(step("unblock", n))
    for n in args.fix or []:
        pr = pr_of(n)
        ok, why = push_allowed(pr)
        has_desc = bool((pr.get("fix_draft") or {}).get("kind") == "description")
        has_click = bool(pr.get("one_click_suggestions"))
        if not (has_desc or has_click):
            raise ActError(f"--fix {n}: nothing to apply — no drafted description and no one-click suggestions on the row")
        if has_click and not ok:
            raise ActError(f"--fix {n}: {why}")
        steps.append(step("fix", n, description=has_desc, suggestions=has_click))
    if args.close:
        if not args.superseded_by:
            raise ActError("--close needs --superseded-by M")
        pr_of(args.superseded_by)
        steps.append(step("close", args.close, superseded_by=args.superseded_by))
    for n in args.refresh or []:
        pr = pr_of(n)
        reason = args.reason or next((r for r in pr.get("reasons") or [] if r.startswith("review:")), "the review is stale")
        steps.append(step("refresh", n, reason=reason))
    for n in args.rerun or []:
        pr = pr_of(n)
        status = ((pr.get("review") or {}).get("status") or "ABSENT").lower().replace("_", "-")
        reason = args.reason or {"error": "the last review run failed", "absent": "no review ran on this PR",
                                 "triage-prose": "only the triage prose check ran"}.get(status, f"the review is {status}")
        steps.append(step("rerun", n, reason=reason))
    for n in args.render or []:
        steps.append(step("render", n, pages=(pr_of(n).get("preview") or {}).get("pages") or []))
    for n in args.deploy or []:
        steps.append(step("deploy", n))
    if not steps:
        raise ActError("nothing to do: pass --stamp / --route / --unblock / --fix / --close / --refresh / --rerun / --render / --deploy")
    return Plan(PLAN_SCHEMA, queue.get("repo") or gh_client.DEFAULT_REPO, datetime.now(timezone.utc).isoformat(timespec="seconds"),
                {"merge_humans": bool(args.merge_humans), "no_merge": bool(args.no_merge), "force": bool(args.force)}, steps)


def preview(plan_: Plan, queue: dict | None = None) -> str:
    by = {p["number"]: p for p in (queue or {}).get("prs") or []}
    lines = [f"Plan · {plan_.repo} · {len(plan_.steps)} step(s)", ""]
    for i, s in enumerate(plan_.steps, 1):
        head = s.expect_head[:7]
        lines.append(f"{i}. {s.kind.upper():<8} #{s.pr} {s.title}  (@{s.author}, head {head})")
        if s.kind == "stamp":
            lines.append(f"     preflight: head == {head}, mergeable_state ∈ {STAMP_STATES}, checks green, no changes-requested")
            lines.append(f"     POST review APPROVE: \"{approval_body(s.author_type, note=s.args.get('note', ''))}\"")
            lines.append("     PUT merge (squash)" if s.args.get("merge") else f"     no merge — {s.note}")
        elif s.kind == "route":
            lines.append(f"     request review from {s.args['target']}; comment with the row's defects + footer")
            pr = by.get(s.pr) or {}
            for r in (pr.get("reasons") or [])[:6]:
                lines.append(f"       · {r}")
        elif s.kind == "request-changes":
            lines.append("     POST review CHANGES_REQUESTED + label needs-author-response; body:")
            for ln in request_changes_body(by.get(s.pr) or {}, s.args.get("note", "")).splitlines():
                lines.append(f"       {ln}")
        elif s.kind == "unblock":
            lines.append(f"     git: fetch, checkout {s.branch}, merge origin/master --no-ff, push (abort on conflict)"
                         + (f"  [chain {s.args['chain']}: next link]" if s.args.get("chain") else ""))
        elif s.kind == "fix":
            lines.append("     " + ", ".join(k for k in ("description", "suggestions") if s.args.get(k)) + " → commit + push")
        elif s.kind == "close":
            lines.append(f"     comment on #{s.pr} and #{s.args['superseded_by']} (footer), then close #{s.pr}")
        elif s.kind == "refresh":
            lines.append(f"     comment: @claude {s.args['reason']} #update-review (footer)")
        elif s.kind == "rerun":
            lines.append(f"     comment: @claude {s.args['reason']} #new-review (footer) — clears the cards, fresh review from scratch")
        elif s.kind == "render":
            lines.append(f"     screenshot {len(s.args.get('pages') or [])} preview page(s) → {SHOTS_DIR}/{s.pr}/")
        elif s.kind == "deploy":
            lines.append(f"     dispatch {DEPLOY_WORKFLOW} @ {s.branch}")
    lines += ["", "Run: act.py --execute <plan.json>   (add --dry-run to log the writes without sending them)"]
    return "\n".join(lines) + "\n"


# ---- git ------------------------------------------------------------------------


class Git:
    """Thin subprocess wrapper; every method is stubbed in tests."""

    def __init__(self, repo_root: Path = _REPO_ROOT):
        self.root = repo_root

    def run(self, *args: str, check: bool = True) -> subprocess.CompletedProcess:
        return subprocess.run(["git", *args], cwd=self.root, text=True, capture_output=True, check=check)

    def current_branch(self) -> str:
        return self.run("rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    def is_clean(self) -> bool:
        return not self.run("status", "--porcelain").stdout.strip()

    def fetch(self, *refs: str) -> None:
        self.run("fetch", "origin", *refs)

    def checkout_tracking(self, branch: str) -> None:
        self.run("checkout", "-B", branch, f"origin/{branch}")

    def checkout(self, branch: str) -> None:
        self.run("checkout", branch)

    def merge(self, ref: str) -> bool:
        """True when the merge completed; False when it stopped on conflicts."""
        return self.run("merge", "--no-ff", "--no-edit", ref, check=False).returncode == 0

    def conflicted_files(self) -> list[str]:
        return [l for l in self.run("diff", "--name-only", "--diff-filter=U").stdout.splitlines() if l]

    def abort_merge(self) -> None:
        self.run("merge", "--abort", check=False)

    def add(self, *paths: str) -> None:
        self.run("add", "--", *paths)

    def commit(self, message: str) -> str:
        self.run("commit", "-m", message)
        return self.run("rev-parse", "HEAD").stdout.strip()

    def push(self, branch: str) -> None:
        self.run("push", "origin", f"HEAD:{branch}")  # never --force


def apply_suggestion(root: Path, path: str, start_line: int, end_line: int, replacement: str) -> None:
    f = root / path
    lines = f.read_text().splitlines(keepends=True)
    new = [l if l.endswith("\n") else l + "\n" for l in replacement.splitlines()]
    lines[start_line - 1:end_line] = new
    f.write_text("".join(lines))


SUGGESTION_RE = re.compile(r"```suggestion\n(.*?)```", re.S)


def commit_message(subject: str) -> str:
    trailer = os.environ.get(COMMIT_TRAILER_ENV, "").strip()
    return subject + (f"\n\n{trailer}" if trailer else "")


# ---- execution --------------------------------------------------------------------


def preflight(gh: GhClient, s: Step) -> tuple[bool, str, dict]:
    """Re-fetch the PR immediately before merging. master moves during a
    batch and a squash earlier in this run can dirty a later PR."""
    detail = collect.fetch_detail(gh, s.pr)
    head = (detail.get("head") or {}).get("sha") or ""
    if detail.get("state", "open") != "open":
        return False, f"head-state: PR is {detail.get('state')}", detail
    if s.expect_head and head != s.expect_head:
        return False, f"head-moved: planned {s.expect_head[:7]}, now {head[:7]} — re-collect and re-plan", detail
    ms = detail.get("mergeable_state") or "unknown"
    if ms not in STAMP_STATES:
        return False, f"mergeable_state={ms}", detail
    checks = collect.checks_rollup(gh.check_runs(head), gh.commit_statuses(head))
    if checks["state"] != "green":
        return False, f"checks {checks['state']}: {', '.join(checks['failing'] or checks['pending'])}", detail
    latest: dict[str, str] = {}
    for r in sorted(gh.reviews(s.pr), key=lambda r: r.get("submitted_at") or ""):
        if ((r.get("user") or {}).get("type") or "") != "Bot" and r.get("state") in ("APPROVED", "CHANGES_REQUESTED"):
            latest[(r.get("user") or {}).get("login") or ""] = r["state"]
    if "CHANGES_REQUESTED" in latest.values():
        who = [u for u, st in latest.items() if st == "CHANGES_REQUESTED"]
        return False, f"changes requested by {', '.join(who)}", detail
    return True, "ok", detail


def open_items(pr: dict) -> list[dict]:
    return [i for i in (pr.get("review") or {}).get("items") or []
            if not i.get("disposition") and i.get("bucket") not in ("style", "pre-existing", "preexisting")]


def request_changes_body(pr: dict, note: str = "") -> str:
    """references/message-templates.md, Request changes row: line-anchored
    issues, no filler; the bot variant names the issue and what to change.
    A judgment's `ask` is the author-facing sentence; `decision` (the
    question the approver answered) stands in when there is no `ask`. The
    `note` is the approver's rationale and never leaves the board. Open
    findings fill in when the judge step didn't run on the row."""
    lines = []
    if note.strip():
        lines.append(note.strip())
    items = pr.get("judgments") or []
    if items:
        for j in items:
            where = f"`{j['file']}` L{j['line']}: " if j.get("file") and j.get("line") else ""
            ask = (j.get("ask") or j.get("decision") or "").strip()
            if not ask:
                continue
            lines.append(f"- {where}{ask}")
    else:
        for i in open_items(pr):
            where = f"`{i['file']}` {i.get('anchor') or ''}: " if i.get("file") else f"{i.get('anchor') or ''}: "
            lines.append(f"- {where}{(i.get('summary') or i.get('text') or '').strip()}")
    atype = (pr.get("author") or {}).get("type")
    if atype == "external":
        lines = ["Thanks for this. A few things before it can merge:", ""] + lines + ["", "Mention @claude if you need help."]
    elif atype == "bot":
        lines.append("")
        lines.append("Answer each with `@claude F<n>: <reason> #update-review`, or push the fix.")
    return "\n".join(lines).strip()


def _defect_comment(pr: dict, target: str) -> str:
    lines = [f"Routing to {target}: this is a {'/'.join(pr.get('domains') or ['?'])} change, not mine to approve."]
    # Only what a reviewer acts on. The queue's own proxies (desc:, brief:,
    # blog:, cluster:, review:) are noise to anyone who isn't running it.
    defects = [r for r in pr.get("reasons") or [] if r.split(":")[0] in
               ("warnings", "outstanding", "self-accepted", "directional", "duplicate", "merging-over")]
    if defects:
        lines.append("")
        lines.append("What the queue flagged:")
        lines += [f"- `{d}`" for d in defects]
    for j in pr.get("judgments") or []:
        lines.append("")
        head = f"**{j.get('finding_id') or ''}** {j.get('decision') or ''}".strip()
        lines.append(head)
        if j.get("deep_link"):
            lines.append(f"  {j['deep_link']}")
        if j.get("disposition"):
            lines.append(f"  suggested: {j['disposition']}")
    return with_footer("\n".join(lines))


def execute(plan_: Plan, gh: GhClient, git: Git | None = None, *, queue: dict | None = None,
            dry_run: bool = False, repo_root: Path = _REPO_ROOT, node: str = "node") -> list[Result]:
    by = {p["number"]: p for p in (queue or {}).get("prs") or []}
    results: list[Result] = []
    for s in plan_.steps:
        before = len(gh.writes)
        try:
            if dry_run and s.kind in ("stamp", "route", "request-changes", "fix", "close", "refresh", "rerun", "deploy"):
                ok, msg = True, f"dry-run: would {s.kind} #{s.pr}"
                if s.kind == "stamp":
                    pf_ok, pf_msg, _ = preflight(gh, s)
                    ok, msg = pf_ok, f"dry-run preflight {pf_msg}"
            elif s.kind == "stamp":
                ok, msg = _stamp(gh, s)
            elif s.kind == "route":
                pr = by.get(s.pr) or {}
                ok, msg = _route(gh, s, pr)
            elif s.kind == "request-changes":
                pr = by.get(s.pr) or {}
                gh.create_review(s.pr, "REQUEST_CHANGES", request_changes_body(pr, s.args.get("note", "")))
                gh.add_labels(s.pr, ["needs-author-response"])
                ok, msg = True, "changes requested; needs-author-response applied"
            elif s.kind == "unblock":
                ok, msg = _unblock(git or Git(repo_root), s, dry_run=dry_run)
            elif s.kind == "fix":
                ok, msg = _fix(gh, git or Git(repo_root), s, by.get(s.pr) or {}, repo_root)
            elif s.kind == "close":
                ok, msg = _close(gh, s)
            elif s.kind == "refresh":
                gh.comment(s.pr, with_footer(f"@claude {s.args['reason']} #update-review"))
                ok, msg = True, "refresh requested"
            elif s.kind == "rerun":
                gh.comment(s.pr, with_footer(f"@claude {s.args['reason']} #new-review"))
                ok, msg = True, "fresh review requested"
            elif s.kind == "render":
                ok, msg = _render(s, node=node)
            elif s.kind == "deploy":
                gh.dispatch_workflow(DEPLOY_WORKFLOW, s.branch)
                ok, msg = True, f"dispatched {DEPLOY_WORKFLOW} @ {s.branch}"
            else:
                ok, msg = False, f"unknown step kind {s.kind}"
        except (GhError, ActError, subprocess.CalledProcessError, OSError) as exc:
            ok, msg = False, f"{type(exc).__name__}: {exc}"
        results.append(Result(s, ok, msg, gh.writes[before:]))
    return results


def _stamp(gh: GhClient, s: Step) -> tuple[bool, str]:
    ok, msg, detail = preflight(gh, s)
    if not ok:
        return False, f"preflight refused: {msg}"
    trust = "high"
    gh.create_review(s.pr, "APPROVE", approval_body(s.author_type, trust, s.args.get("note", "")))
    if not s.args.get("merge"):
        return True, "approved (not merged)"
    gh.merge(s.pr, (detail.get("head") or {}).get("sha") or s.expect_head, "squash")
    return True, "approved and squash-merged"


def _route(gh: GhClient, s: Step, pr: dict) -> tuple[bool, str]:
    target = s.args["target"].lstrip("@")
    if "/" in target:
        gh.request_reviewers(s.pr, [], [target.split("/", 1)[1]])
    else:
        gh.request_reviewers(s.pr, [target], [])
    gh.comment(s.pr, _defect_comment(pr, "@" + target))
    return True, f"review requested from @{target}"


def _unblock(git: Git, s: Step, *, dry_run: bool = False) -> tuple[bool, str]:
    if not s.branch:
        return False, "no head branch on the step"
    if not git.is_clean():
        return False, "working tree is not clean; stash or commit first"
    start = git.current_branch()
    try:
        git.fetch("master", s.branch)
        git.checkout_tracking(s.branch)
        if git.merge("origin/master"):
            if dry_run:
                return True, "dry-run: base merged cleanly (not pushed)"
            git.push(s.branch)
            return True, "merged origin/master into the head branch and pushed"
        conflicts = git.conflicted_files()
        git.abort_merge()
        return False, "conflicts need a human: " + ", ".join(conflicts[:8])
    finally:
        if start and start != s.branch:
            git.checkout(start)


def _fix(gh: GhClient, git: Git, s: Step, pr: dict, repo_root: Path) -> tuple[bool, str]:
    done = []
    if s.args.get("description"):
        body = (pr.get("fix_draft") or {}).get("body")
        if not body:
            return False, "no drafted description on the row"
        gh.update_pr(s.pr, body=body)
        done.append("description")
    if s.args.get("suggestions"):
        suggestions = pr.get("one_click_suggestions") or []
        if not git.is_clean():
            return False, "working tree is not clean; stash or commit first"
        start = git.current_branch()
        try:
            git.fetch(s.branch)
            git.checkout_tracking(s.branch)
            applied = 0
            for sg in suggestions:
                m = SUGGESTION_RE.search(sg.get("body") or "")
                if not m or not sg.get("path") or not sg.get("line"):
                    continue
                end = int(sg["line"])
                start_line = int(sg.get("start_line") or sg.get("original_start_line") or end)
                apply_suggestion(repo_root, sg["path"], start_line, end, m.group(1))
                git.add(sg["path"])
                applied += 1
            if applied:
                git.commit(commit_message(f"Apply {applied} review suggestion(s)"))
                git.push(s.branch)
                done.append(f"{applied} suggestion(s)")
        finally:
            if start and start != s.branch:
                git.checkout(start)
    return True, "applied " + ", ".join(done) if done else "nothing applied"


def _close(gh: GhClient, s: Step) -> tuple[bool, str]:
    m = s.args["superseded_by"]
    gh.comment(s.pr, with_footer(f"Closing in favor of #{m}, which covers the same change."))
    gh.comment(m, with_footer(f"Supersedes #{s.pr}, closed as a duplicate."))
    gh.close_pr(s.pr)
    return True, f"closed; superseded by #{m}"


def _render(s: Step, *, node: str = "node") -> tuple[bool, str]:
    pages = s.args.get("pages") or []
    if not pages:
        return False, "no preview pages on the row (no content/*.md changes, or the preview isn't built yet)"
    out_dir = SHOTS_DIR / str(s.pr)
    out_dir.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ)
    env.setdefault("NODE_PATH", "/opt/node22/lib/node_modules")
    shots = []
    for pg in pages:
        url = pg.get("preview_url")
        if not url:
            return False, "preview URL not posted yet (pulumi-bot's preview comment is missing)"
        slug = (pg.get("url") or "").strip("/").replace("/", "_") or "index"
        out = out_dir / f"{slug}.png"
        subprocess.run([node, str(_HERE / "screenshot.mjs"), str(out), url, "--full"], check=True, env=env,
                       capture_output=True, text=True)
        shots.append(str(out))
    return True, f"{len(shots)} screenshot(s) → {out_dir}"


def report(results: list[Result]) -> str:
    lines = []
    for r in results:
        mark = "✓" if r.ok else "✗"
        lines.append(f"{mark} {r.step.kind:<8} #{r.step.pr}: {r.message}")
    n_ok = sum(1 for r in results if r.ok)
    lines.append(f"{n_ok}/{len(results)} step(s) succeeded. Re-collect to refresh the board.")
    return "\n".join(lines) + "\n"


# ---- CLI ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--in", dest="inp", default=str(_REPO_ROOT / ".pr-review-queue.json"))
    ap.add_argument("--stamp", help="comma list of PR numbers")
    ap.add_argument("--route", action="append", help="N:@user or N:@org/team (repeatable; N alone uses the row's route action)")
    ap.add_argument("--request-changes", type=int, action="append", help="send the row's judgments back to the author as a changes-requested review")
    ap.add_argument("--chain", action="append", metavar="C1", help="stamp a cluster's first PR, then unblock the next")
    ap.add_argument("--unblock", type=int, action="append")
    ap.add_argument("--fix", type=int, action="append")
    ap.add_argument("--close", type=int)
    ap.add_argument("--superseded-by", type=int)
    ap.add_argument("--refresh", type=int, action="append")
    ap.add_argument("--rerun", type=int, action="append", help="post `@claude <reason> #new-review`: a fresh review from scratch")
    ap.add_argument("--reason", help="for --refresh / --rerun: what changed; for --request-changes: an opening line")
    ap.add_argument("--render", type=int, action="append")
    ap.add_argument("--deploy", type=int, action="append")
    ap.add_argument("--merge-humans", action="store_true", help="squash-merge human-authored stamps too")
    ap.add_argument("--no-merge", action="store_true", help="approve only")
    ap.add_argument("--force", action="store_true", help="stamp a judge row (approve as-is)")
    ap.add_argument("--approve-note", help="one sentence appended to the approval body")
    ap.add_argument("--plan-out", default=str(_REPO_ROOT / ".pr-review-plan.json"))
    ap.add_argument("--execute", metavar="PLAN.json", help="run a plan written earlier")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--backend", default="auto", choices=("auto", "gh", "rest", "snapshot"))
    ap.add_argument("--snapshot-dir")
    ap.add_argument("--self-test", action="store_true")
    return ap


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.self_test:
        import test_act  # noqa: PLC0415 — the pytest file doubles as the harness
        return test_act.run_standalone()
    queue = json.loads(Path(args.inp).read_text()) if Path(args.inp).exists() else {}
    if args.execute:
        plan_ = Plan.from_json(json.loads(Path(args.execute).read_text()))
        gh = GhClient(plan_.repo, args.backend, snapshot_dir=args.snapshot_dir)
        results = execute(plan_, gh, queue=queue, dry_run=args.dry_run)
        sys.stdout.write(report(results))
        return 0 if all(r.ok for r in results) else 1
    try:
        plan_ = plan(queue, args)
    except ActError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    Path(args.plan_out).write_text(json.dumps(plan_.to_json(), indent=1) + "\n")
    sys.stdout.write(preview(plan_, queue))
    print(f"plan → {args.plan_out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
