#!/usr/bin/env python3
"""Tests for act.py — the push policy, approval voice, planning guards, the
stamp preflight (refuses a moved head, accepts `blocked` only with green
checks, continues after a failure), route/close/refresh comments with the
footer, --fix, and --unblock over a stub git.

Runs under pytest and standalone via `act.py --self-test`. No pytest
fixtures; GitHub is the snapshot backend (writes land in writes.jsonl).
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import act  # noqa: E402
import analyze  # noqa: E402
import collect  # noqa: E402
import routing  # noqa: E402
from gh_client import GhClient, snapshot_path  # noqa: E402
from test_analyze import CONFIG, TODAY, cfg, row  # noqa: E402
from test_analyze import stampable as _stampable  # noqa: E402
from test_collect import make_snapshot, patch_for  # noqa: E402


def stampable(number: int = 100, **over) -> dict:
    """test_analyze.stampable with a per-PR file and title, so a batch of
    fixtures never collides with itself."""
    over.setdefault("title", f"Change page {number}")
    over.setdefault("files", [{"filename": f"content/docs/p{number}.md", "status": "modified", "additions": 1, "deletions": 1,
                               "patch": patch_for(["new line"], lines_removed=["old line"])}])
    return _stampable(number, **over)


class Env:
    """A snapshot dir + collected/analyzed queue that stays alive for the test."""

    def __init__(self, specs: list[dict], user_cfg=None):
        self.td = tempfile.TemporaryDirectory()
        self.root = Path(self.td.name)
        self.specs = specs
        make_snapshot(self.root, specs)
        self.gh = GhClient("pulumi/docs", "snapshot", snapshot_dir=self.root)
        q = collect.collect(self.gh, cache_dir=None, repo_root=self.root, workers=1)
        self.queue = analyze.analyze(q, user_cfg or cfg(), config=CONFIG, repo_root=self.root, aliases=set(), today=TODAY)

    def writes(self) -> list[dict]:
        f = self.root / "writes.jsonl"
        return [json.loads(l) for l in f.read_text().splitlines()] if f.exists() else []

    def move_head(self, number: int, new_sha: str) -> None:
        f = snapshot_path(self.root, "GET", f"repos/pulumi/docs/pulls/{number}", None)
        d = json.loads(f.read_text())
        d["head"]["sha"] = new_sha
        f.write_text(json.dumps(d))

    def set_detail(self, number: int, **fields) -> None:
        f = snapshot_path(self.root, "GET", f"repos/pulumi/docs/pulls/{number}", None)
        d = json.loads(f.read_text())
        d.update(fields)
        f.write_text(json.dumps(d))

    def close(self):
        self.td.cleanup()


def args(**kw) -> argparse.Namespace:
    ns = act.build_parser().parse_args([])
    for k, v in kw.items():
        setattr(ns, k, v)
    return ns


# ---- policy ----------------------------------------------------------------


def test_push_policy_for_bot_branches():
    ok, _ = act.push_allowed({"author": {"login": "dependabot[bot]"}, "labels": [], "head": {}})
    assert ok is False
    ok, _ = act.push_allowed({"author": {"login": "pulumi-bot"}, "labels": ["automation/merge"], "head": {}})
    assert ok is False
    ok, _ = act.push_allowed({"author": {"login": "pulumi-bot"}, "labels": ["content-review/glow-up"], "head": {}})
    assert ok is True
    ok, why = act.push_allowed({"author": {"login": "workprentice[bot]"}, "labels": [], "head": {"is_fork": False}})
    assert ok is True and "merge commits" in why
    assert act.push_allowed({"author": {"login": "someone"}, "labels": [], "head": {"is_fork": True}})[0] is False


def test_approval_body_follows_message_templates_and_footer_rule():
    assert act.approval_body("bot") == "Approved."
    assert act.approval_body("internal") == "LGTM."
    assert act.approval_body("external", "low") == "Thanks! LGTM. Welcome to Pulumi. 🎉"
    assert act.approval_body("internal", note="Double-check the flag on line 42.") == "LGTM. Double-check the flag on line 42."
    assert "Generated by [Claude Code]" not in act.approval_body("bot")
    assert act.with_footer("hi").endswith("_Generated by [Claude Code](https://claude.ai/code)_")


# ---- planning ----------------------------------------------------------------


def test_plan_guards():
    env = Env([stampable(1), stampable(2, mergeable_state="dirty"), stampable(3, labels=["review:trivial"])])
    try:
        for bad, msg in ((args(stamp="3"), "not stamp"), (args(stamp="2", force=True), "blocked"), (args(stamp="9"), "not in the queue"),
                         (args(close=1), "--superseded-by"), (args(fix=[1]), "nothing to apply"), (args(), "nothing to do"),
                         (args(route=["1:"]), "no target")):
            try:
                act.plan(env.queue, bad)
                raise AssertionError(f"plan accepted {bad}")
            except act.ActError as exc:
                assert msg in str(exc), str(exc)
        p = act.plan(env.queue, args(stamp="1", force=False))
        assert [s.kind for s in p.steps] == ["stamp"] and p.steps[0].expect_head == row(env.queue, 1)["head"]["sha"]
        assert p.steps[0].args["merge"] is True  # bot author
        forced = act.plan(env.queue, args(stamp="3", force=True))
        assert forced.steps[0].args["merge"] is True and forced.options["force"] is True
    finally:
        env.close()


def test_stamping_records_the_calls_before_it_merges():
    env = Env([stampable(1)])
    try:
        r = row(env.queue, 1)
        r["judgments"] = [
            {"finding_id": "F6", "disposition": "refuted", "decision": "Does the sentence claim that?",
             "note": "Spurious: the list is what the team wants to build, not the target page."},
            {"finding_id": "F7", "disposition": "accepted", "note": "Pre-existing; both bullets already shared the link."},
            {"finding_id": "T1", "disposition": "refuted", "note": "Triage misread the item count."},   # not a card finding
            {"finding_id": "F9", "disposition": "deferred", "note": "The author's to fix."},            # goes back, not resolved
        ]
        p = act.plan(env.queue, args(stamp="1"))
        assert p.steps[0].args["resolves"] == [
            "/resolve F6 refuted: Spurious: the list is what the team wants to build, not the target page.",
            "/resolve F7 accepted: Pre-existing; both bullets already shared the link."]
        assert "comment: /resolve F6 refuted" in act.preview(p, env.queue)
        res = act.execute(p, env.gh, queue=env.queue)
        assert res[0].ok and "2 findings resolved" in res[0].message
        w = env.writes()
        # the record lands before the approval, so a merge never outruns it
        assert w[0]["path"].endswith("/issues/1/comments") and "/resolve F6 refuted" in w[0]["body"]["body"]
        assert "F9" not in w[0]["body"]["body"] and "T1" not in w[0]["body"]["body"]
        assert w[1]["path"].endswith("/pulls/1/reviews") and w[1]["body"]["event"] == "APPROVE"
        assert w[2]["method"] == "PUT"
    finally:
        env.close()


def test_per_pr_merge_mode_beats_the_author_default():
    env = Env([stampable(1), stampable(2, author="camsoper", author_type="User")])
    try:
        p = act.plan(env.queue, args(stamp="1:no-merge,2:merge", force=True))
        by = {s.pr: s for s in p.steps}
        assert by[1].args["merge"] is False and "asked not to merge" in by[1].note
        assert by[2].args["merge"] is True and by[2].note == ""
        # the blanket flags still work, and the default is unchanged
        d = {s.pr: s.args["merge"] for s in act.plan(env.queue, args(stamp="1,2", force=True)).steps}
        assert d == {1: True, 2: False}
        try:
            act.plan(env.queue, args(stamp="1:squash", force=True))
            raise AssertionError("expected refusal: unknown mode")
        except act.ActError as exc:
            assert ":merge and :no-merge" in str(exc)
    finally:
        env.close()


def test_plan_human_stamp_is_approve_only_unless_merge_humans():
    env = Env([stampable(1, author="camsoper", author_type="User")])
    try:
        p = act.plan(env.queue, args(stamp="1", force=True))
        assert p.steps[0].args["merge"] is False and "approve only" in p.steps[0].note
        p = act.plan(env.queue, args(stamp="1", force=True, merge_humans=True))
        assert p.steps[0].args["merge"] is True
        p = act.plan(env.queue, args(stamp="1", force=True, merge_humans=True, no_merge=True))
        assert p.steps[0].args["merge"] is False
        text = act.preview(p, env.queue)
        assert "no merge" in text and "POST review APPROVE" in text
    finally:
        env.close()


def test_plan_roundtrips_through_json_and_route_target_defaults_to_row_action():
    env = Env([stampable(1)], cfg(me=["blog"]))
    try:
        p = act.plan(env.queue, args(route=["1"]))
        assert p.steps[0].args["target"] == "@pulumi/docs-guild"
        again = act.Plan.from_json(json.loads(json.dumps(p.to_json())))
        assert again.steps[0].args == p.steps[0].args and again.steps[0].expect_head == p.steps[0].expect_head
    finally:
        env.close()


# ---- stamp preflight -----------------------------------------------------------


def test_stamp_preflight_refuses_moved_head_and_writes_nothing():
    env = Env([stampable(1)])
    try:
        p = act.plan(env.queue, args(stamp="1"))
        env.move_head(1, "e" * 40)
        res = act.execute(p, env.gh, queue=env.queue)
        assert res[0].ok is False and "head-moved" in res[0].message
        assert env.writes() == []
    finally:
        env.close()


def test_stamp_blocked_state_needs_green_checks_and_no_changes_requested():
    env = Env([stampable(1, mergeable_state="blocked")])
    try:
        p = act.plan(env.queue, args(stamp="1"))
        res = act.execute(p, env.gh, queue=env.queue)
        assert res[0].ok and "squash-merged" in res[0].message
        w = env.writes()
        assert [x["method"] for x in w] == ["POST", "PUT"]
        assert w[0]["body"] == {"event": "APPROVE", "body": "Approved."} and w[1]["body"]["merge_method"] == "squash"
    finally:
        env.close()
    # The plan refuses a blocked row outright; the preflight is the second net
    # for a PR that went red or dirty between plan and execute.
    env = Env([stampable(1, mergeable_state="blocked", check_runs=[{"name": "lint", "status": "completed", "conclusion": "failure"}])])
    try:
        s = act.Step("stamp", 1, {"merge": True}, expect_head=row(env.queue, 1)["head"]["sha"])
        res = act.execute(act.Plan(1, "pulumi/docs", "", {}, [s]), env.gh, queue=env.queue)
        assert res[0].ok is False and "checks red: lint" in res[0].message and env.writes() == []
    finally:
        env.close()
    env = Env([stampable(1, mergeable_state="dirty")])
    try:
        s = act.Step("stamp", 1, {"merge": True}, expect_head=row(env.queue, 1)["head"]["sha"])
        ok, msg, _ = act.preflight(env.gh, s)
        assert ok is False and "mergeable_state=dirty" in msg
    finally:
        env.close()
    env = Env([stampable(1, reviews=[{"user": {"login": "cnunciato", "type": "User"}, "state": "CHANGES_REQUESTED", "submitted_at": "2026-09-12T00:00:00Z"}])])
    try:
        s = act.Step("stamp", 1, {"merge": True}, expect_head=row(env.queue, 1)["head"]["sha"])
        ok, msg, _ = act.preflight(env.gh, s)
        assert ok is False and "changes requested by cnunciato" in msg
    finally:
        env.close()


def test_stamp_batch_continues_after_a_failure():
    env = Env([stampable(1), stampable(2, title="Second page", files=[{"filename": "content/docs/b.md", "status": "modified", "additions": 1, "deletions": 1, "patch": "@@ -1,1 +1,1 @@\n-o\n+n"}])])
    try:
        p = act.plan(env.queue, args(stamp="1,2"))
        env.move_head(1, "e" * 40)
        res = act.execute(p, env.gh, queue=env.queue)
        assert [r.ok for r in res] == [False, True]
        assert [w["path"] for w in env.writes()] == ["repos/pulumi/docs/pulls/2/reviews", "repos/pulumi/docs/pulls/2/merge"]
        text = act.report(res)
        assert "1/2 step(s) succeeded" in text
    finally:
        env.close()


def test_dry_run_runs_preflight_but_writes_nothing():
    env = Env([stampable(1)])
    try:
        p = act.plan(env.queue, args(stamp="1"))
        res = act.execute(p, env.gh, queue=env.queue, dry_run=True)
        assert res[0].ok and "dry-run" in res[0].message and env.writes() == []
    finally:
        env.close()


# ---- route / close / refresh ---------------------------------------------------------


def test_route_team_vs_user_and_defect_comment_carries_footer():
    env = Env([stampable(1, comments=[]), stampable(2, comments=[])], cfg(me=["blog"]))
    try:
        p = act.plan(env.queue, args(route=["1:@pulumi/docs-guild", "2:@cnunciato"]))
        res = act.execute(p, env.gh, queue=env.queue)
        assert all(r.ok for r in res)
        w = env.writes()
        assert w[0]["path"].endswith("/pulls/1/requested_reviewers") and w[0]["body"] == {"team_reviewers": ["docs-guild"]}
        assert w[2]["body"] == {"reviewers": ["cnunciato"]}
        comment = w[1]["body"]["body"]
        assert comment.startswith("Routing to @pulumi/docs-guild: this is a docs change, not mine to approve.")
        assert comment.endswith("_Generated by [Claude Code](https://claude.ai/code)_")
        assert "—" not in comment and "review:absent" not in comment  # the queue's own proxies stay off the PR
    finally:
        env.close()


def test_request_changes_posts_a_review_from_the_judgments_and_labels():
    env = Env([stampable(1, labels=["review:trivial"]), stampable(2, labels=["review:trivial"])])
    try:
        row(env.queue, 1)["judgments"] = [{"finding_id": "L1-7", "file": "content/docs/best-practices/_index.md", "line": 1,
                                          "decision": "Nest the page or make it top-level?", "ask": "Give the page a nav home under Concepts.",
                                          "disposition": "deferred", "note": "Cam's IA call; never sent to the author."}]
        try:
            act.plan(env.queue, args(request_changes=[2]))
            raise AssertionError("expected refusal: nothing to send back")
        except act.ActError as exc:
            assert "nothing to send back" in str(exc)
        p = act.plan(env.queue, args(request_changes=[1], reason="Two things before this merges:"))
        text = act.preview(p, env.queue)
        assert "CHANGES_REQUESTED" in text and "Give the page a nav home under Concepts." in text and "IA call" not in text
        res = act.execute(p, env.gh, queue=env.queue)
        assert res[0].ok
        w = env.writes()
        assert w[0]["path"].endswith("/pulls/1/reviews") and w[0]["body"]["event"] == "REQUEST_CHANGES"
        body = w[0]["body"]["body"]
        assert body.startswith("Two things before this merges:") and "`content/docs/best-practices/_index.md` L1: Give the page a nav home under Concepts." in body
        assert "IA call" not in body  # the approver's note stays on the board
        assert "#update-review" in body  # bot author: tell it how to answer
        assert "Generated by [Claude Code]" not in body  # a review body, not a bot comment
        assert w[1]["path"].endswith("/issues/1/labels") and w[1]["body"] == {"labels": ["needs-author-response"]}
    finally:
        env.close()


def test_a_workflow_author_is_closed_not_sent_back():
    env = Env([stampable(1, labels=["review:trivial"], author="pulumi-bot", author_type="User")])
    try:
        r = row(env.queue, 1)
        r["judgments"] = [{"finding_id": "M1", "file": "content/docs/p1.md", "line": 182,
                           "decision": "The lead-in folds into the bullet above it.",
                           "ask": "Add a blank line before the lead-in.", "disposition": "deferred"}]
        try:
            act.plan(env.queue, args(request_changes=[1]))
            raise AssertionError("expected refusal: pulumi-bot never reads a review")
        except act.ActError as exc:
            assert "is a workflow, not an author" in str(exc) and "--close 1" in str(exc)
        act.plan(env.queue, args(request_changes=[1], force=True))  # the approver can still insist
        p = act.plan(env.queue, args(close=1))  # no --reason needed: the row writes its own
        res = act.execute(p, env.gh, queue=env.queue)
        assert res[0].ok
        w = env.writes()
        body = w[0]["body"]["body"]
        assert w[0]["path"].endswith("/issues/1/comments")
        assert "opened by a workflow run" in body and "Add a blank line before the lead-in." in body
        assert "#update-review" not in body and "re-queues the page" in body
        assert body.endswith("_Generated by [Claude Code](https://claude.ai/code)_")
        assert w[1]["method"] == "PATCH" and w[1]["body"] == {"state": "closed"}
    finally:
        env.close()


def test_request_changes_body_voice_by_author_type():
    ext = {"author": {"type": "external"}, "judgments": [{"decision": "Fix the count.", "file": "a.md", "line": 3}]}
    b = act.request_changes_body(ext)
    assert b.startswith("Thanks for this.") and b.endswith("Mention @claude if you need help.")
    internal = {"author": {"type": "internal"}, "judgments": [], "review": {"items": [{"id": "F1", "bucket": "outstanding", "file": "a.md", "anchor": "L3", "summary": "Wrong count."}]}}
    assert act.request_changes_body(internal) == "- `a.md` L3: Wrong count."


def test_rerun_posts_a_new_review_mention_with_a_status_reason():
    env = Env([stampable(1, labels=["review:error", "domain:docs"]), stampable(2)])
    try:
        p = act.plan(env.queue, args(rerun=[1, 2]))
        assert "#new-review" in act.preview(p)
        res = act.execute(p, env.gh, queue=env.queue)
        assert all(r.ok for r in res)
        w = env.writes()
        assert w[0]["body"]["body"].startswith("@claude the last review run failed #new-review") and w[0]["path"].endswith("/issues/1/comments")
        assert w[0]["body"]["body"].endswith("(https://claude.ai/code)_")
        assert w[1]["body"]["body"].startswith("@claude the review is current #new-review")
    finally:
        env.close()


def test_close_cross_links_and_refresh_mention():
    env = Env([stampable(1), stampable(2)])
    try:
        p = act.plan(env.queue, args(close=1, superseded_by=2, refresh=[2], reason="the label lied"))
        res = act.execute(p, env.gh, queue=env.queue)
        assert all(r.ok for r in res)
        w = env.writes()
        assert "Closing in favor of #2" in w[0]["body"]["body"] and w[0]["path"].endswith("/issues/1/comments")
        assert "Supersedes #1" in w[1]["body"]["body"] and w[1]["path"].endswith("/issues/2/comments")
        assert w[2]["method"] == "PATCH" and w[2]["body"] == {"state": "closed"}
        assert w[3]["body"]["body"].startswith("@claude the label lied #update-review") and w[3]["body"]["body"].endswith("(https://claude.ai/code)_")
    finally:
        env.close()


# ---- fix / unblock ---------------------------------------------------------------


def test_fix_description_uses_the_drafted_body():
    env = Env([stampable(1)])
    try:
        row(env.queue, 1)["fix_draft"] = {"kind": "description", "body": "### Proposed changes\n\nAccurate now."}
        p = act.plan(env.queue, args(fix=[1]))
        res = act.execute(p, env.gh, queue=env.queue)
        assert res[0].ok and env.writes()[0]["body"] == {"body": "### Proposed changes\n\nAccurate now."}
    finally:
        env.close()


class FakeGit:
    def __init__(self, merge_ok=True, conflicts=("content/docs/a.md",)):
        self.merge_ok, self.conflicts, self.calls = merge_ok, list(conflicts), []

    def current_branch(self):
        return "master"

    def is_clean(self):
        return True

    def fetch(self, *refs):
        self.calls.append(("fetch", refs))

    def checkout_tracking(self, b):
        self.calls.append(("checkout_tracking", b))

    def checkout(self, b):
        self.calls.append(("checkout", b))

    def merge(self, ref):
        self.calls.append(("merge", ref))
        return self.merge_ok

    def conflicted_files(self):
        return self.conflicts

    def abort_merge(self):
        self.calls.append(("abort",))

    def push(self, b):
        self.calls.append(("push", b))

    def add(self, *p):
        self.calls.append(("add", p))

    def commit(self, m):
        self.calls.append(("commit", m))
        return "c" * 40


def test_unblock_pushes_only_a_clean_merge_and_returns_to_start_branch():
    env = Env([stampable(1, mergeable_state="dirty")])
    try:
        p = act.plan(env.queue, args(unblock=[1]))
        git = FakeGit(merge_ok=True)
        res = act.execute(p, env.gh, git, queue=env.queue)
        assert res[0].ok and ("push", "branch-1") in git.calls and ("merge", "origin/master") in git.calls
        assert git.calls[-1] == ("checkout", "master")
        git = FakeGit(merge_ok=False)
        res = act.execute(p, env.gh, git, queue=env.queue)
        assert res[0].ok is False and "content/docs/a.md" in res[0].message
        assert ("abort",) in git.calls and not any(c[0] == "push" for c in git.calls)
    finally:
        env.close()


def test_apply_suggestion_replaces_the_line_range():
    with tempfile.TemporaryDirectory() as td:
        f = Path(td) / "a.md"
        f.write_text("one\ntwo\nthree\nfour\n")
        act.apply_suggestion(Path(td), "a.md", 2, 3, "TWO\nTHREE")
        assert f.read_text() == "one\nTWO\nTHREE\nfour\n"


def run_standalone() -> int:
    """The --self-test harness; test list bound at call time (test_sentinel.py)."""
    import inspect  # noqa: PLC0415
    all_tests = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    failures = 0
    for t in all_tests:
        if inspect.signature(t).parameters:
            print(f"  skip: {t.__name__} (pytest fixtures; run via pytest)")
            continue
        try:
            t()
            print(f"  ok: {t.__name__}")
        except AssertionError as exc:
            failures += 1
            print(f"  FAIL: {t.__name__}: {exc}", file=sys.stderr)
        except Exception as exc:  # noqa: BLE001
            failures += 1
            print(f"  FAIL: {t.__name__}: {type(exc).__name__}: {exc}", file=sys.stderr)
    if failures:
        print(f"{failures} act test(s) failed", file=sys.stderr)
        return 1
    print("all act self-tests passed")
    return 0


if __name__ == "__main__":
    sys.exit(run_standalone())
