#!/usr/bin/env python3
"""glowup-autofix.py — the deterministic half of the post-open glow-up autofix.

Pre-verification (preverify-glowup.py) is the primary path: a glow-up PR
should open with every claim on its edited lines verified. This is the
fallback for what the pre-merge review still finds after it opens, since the
review reads the whole diff with more than the claim verifier (a claim the
page's own table contradicts, a sample output the source renders
differently). Those findings are addressed to the PR author, pulumi-bot,
which never answers, so before this they sat open until someone noticed.

One pass, run by `.github/workflows/content-review-glowup-autofix.yml`:

  select    decide, from the PR, its current author card (via
            review-worklist.py's JSON), and prior autofix comments, whether a
            pass should run now:
              fix       open 🚨/❓ findings on a review current at the head,
                        and passes remain
              escalate  findings still open and the pass budget is spent (or
                        the last pass left some unresolved): hand them to
                        the routed human team, once per PR
              none      anything else, with the reason
  answer    validate the model's dispositions against the closed set, fold
            in the deterministic post-check (a fix the re-verification had to
            revert is unresolved, whatever the model said), and render the
            `@claude … #update-review` answer comment, the PR body's
            "Post-open review findings" section, and the escalation comment.

Dispositions (closed set; `address-review:references:dispositions` minus the
two a bot cannot own, `accepted` and `deferred`, which need a human):

  fixed       the text now says what the source says (note: what changed)
  reverted    the glow-up's edit is withdrawn; master's text is back (note)
  refuted     the finding is wrong; `source` must cite what shows it (note)
  unresolved  none of the above could be done safely; a human decides

Bounds. At most MAX_PASSES passes per PR, counted from pulumi-bot comments
carrying the pass marker, and never two passes on the same head: the update
lane refreshes the card after a pass, and only a card current at a NEW head
can start the next one. A PR whose passes are spent escalates once.

Usage:
    glowup-autofix.py select --pr-json pr.json --worklist wl.json \
        --comments comments.json [--max-passes 2]
    glowup-autofix.py answer --select select.json --dispositions d.json \
        [--postcheck reverted.json] --commit <sha> --out-dir .autofix
    glowup-autofix.py --self-test
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

BOT = "pulumi-bot"
BRANCH_PREFIX = "content-review/glowup-"
MAX_PASSES = 2
PASS_MARKER = "GLOWUP_AUTOFIX"
ESCALATED_MARKER = "GLOWUP_AUTOFIX_ESCALATED"
SECTION = "Post-open review findings"
DISPOSITIONS = ("fixed", "reverted", "refuted", "unresolved")
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n"

_PASS_RE = re.compile(rf"<!--\s*{PASS_MARKER}\s+pass=(\d+)\s+head=([0-9a-f]{{7,40}})\s*-->")
_ESC_RE = re.compile(rf"<!--\s*{ESCALATED_MARKER}\b")


def _login(c: dict) -> str:
    return ((c.get("user") or c.get("author") or {}).get("login") or "")


def prior_passes(comments: list[dict]) -> list[dict]:
    out = []
    for c in comments or []:
        if _login(c) != BOT:
            continue
        m = _PASS_RE.search(c.get("body") or "")
        if m:
            out.append({"pass": int(m.group(1)), "head": m.group(2)})
    return out


def escalated(comments: list[dict]) -> bool:
    return any(_login(c) == BOT and _ESC_RE.search(c.get("body") or "") for c in comments or [])


def open_blocking(worklist: dict) -> list[dict]:
    return [i for i in (worklist.get("items") or [])
            if i.get("blocking") and not i.get("disposition")]


def select(pr: dict, worklist: dict, comments: list[dict], max_passes: int = MAX_PASSES) -> dict:
    head = pr.get("headRefOid") or ""
    ref = pr.get("headRefName") or ""
    author = (pr.get("author") or {}).get("login") or ""
    files = [f.get("path") for f in pr.get("files") or [] if f.get("path")]
    md = [f for f in files if f.endswith(".md")]
    base = {"pr": pr.get("number"), "head_sha": head, "head_ref": ref,
            "article": md[0] if len(md) == 1 else "", "open": [], "pass": 0}

    def out(action: str, reason: str, **kw) -> dict:
        return {**base, **kw, "action": action, "reason": reason}

    if author != BOT or not ref.startswith(BRANCH_PREFIX):
        return out("none", f"not a pulumi-bot glow-up ({author or '?'} / {ref or '?'})")
    if (pr.get("state") or "").upper() != "OPEN" or pr.get("isDraft"):
        return out("none", "PR is not open and ready")
    if len(md) != 1:
        return out("none", f"expected exactly one markdown file, found {len(md)}")
    if (worklist.get("surface") or "") != "v3" or worklist.get("parse_confidence") != "high":
        return out("none", "no parseable v3 author card")
    reviewed = worklist.get("reviewed_sha") or ""
    if not head or not reviewed or not head.startswith(reviewed[:7]) or not reviewed.startswith(head[:len(reviewed)]):
        return out("none", f"review is not current at the head ({reviewed[:7] or 'none'} vs {head[:7]})")
    items = open_blocking(worklist)
    if not items:
        return out("none", "no open blocking findings")
    opened = [{"id": i["id"], "bucket": i.get("bucket"), "anchor": i.get("anchor"),
               "summary": i.get("summary", "")} for i in items]
    passes = prior_passes(comments)
    if any(head.startswith(p["head"]) or p["head"].startswith(head[:7]) for p in passes):
        return out("none", "a pass already answered this head; waiting for the refreshed card", open=opened)
    n = max((p["pass"] for p in passes), default=0)
    if n >= max_passes:
        if escalated(comments):
            return out("none", f"pass budget spent ({n}/{max_passes}) and already escalated", open=opened)
        return out("escalate", f"pass budget spent ({n}/{max_passes}) with {len(opened)} finding(s) open",
                   open=opened, **{"pass": n})
    return out("fix", f"{len(opened)} open blocking finding(s); pass {n + 1}/{max_passes}",
               open=opened, **{"pass": n + 1})


def _cell(text, cap: int = 200) -> str:
    t = " ".join(str(text or "").split()).replace("|", "\\|")
    return t if len(t) <= cap else t[: cap - 1] + "…"


def fold(sel: dict, dispositions: dict, postcheck: dict | None) -> list[dict]:
    """One row per open finding: the model's disposition, validated, with the
    post-check applied. Anything missing or malformed is `unresolved`."""
    given = {}
    for d in (dispositions or {}).get("findings") or []:
        if isinstance(d, dict) and d.get("id"):
            given[str(d["id"])] = d
    reverted_ranges = []
    for b in (postcheck or {}).get("blocks") or []:
        lo, hi = (b.get("pristine_lines") or [0, 0])[:2]
        reverted_ranges.append((int(lo), int(hi) if hi else int(lo)))

    def anchor_range(a: str):
        m = re.match(r"^L(\d+)(?:-L?(\d+))?", str(a or ""))
        return (int(m.group(1)), int(m.group(2) or m.group(1))) if m else None

    rows = []
    for f in sel.get("open") or []:
        d = given.get(f["id"], {})
        disp = str(d.get("disposition") or "").strip().lower()
        note = " ".join(str(d.get("note") or "").split())
        source = " ".join(str(d.get("source") or "").split())
        why = ""
        if disp not in DISPOSITIONS:
            disp, why = "unresolved", "no valid disposition recorded"
        elif disp == "refuted" and not source:
            disp, why = "unresolved", "refutation cited no source"
        elif disp in ("fixed", "reverted", "refuted") and not note:
            disp, why = "unresolved", f"{disp} without a note"
        rng = anchor_range(f.get("anchor"))
        if disp in ("fixed", "reverted") and rng and any(lo - 2 <= rng[1] and rng[0] <= hi + 2
                                                         for lo, hi in reverted_ranges):
            disp, why = "unresolved", "the change did not re-verify and was withdrawn"
        rows.append({"id": f["id"], "bucket": f.get("bucket"), "anchor": f.get("anchor"),
                     "summary": f.get("summary", ""), "disposition": disp,
                     "note": note if not why else (f"{why}. {note}".strip() if note else why),
                     "source": source})
    return rows


def render_answer(rows: list[dict], sel: dict, commit: str) -> str:
    """The `#update-review` mention. Only rows with something to record go
    in it; an unresolved row is left for the human the escalation names."""
    lines = []
    for r in rows:
        if r["disposition"] == "fixed":
            lines.append(f"{r['id']}: fixed in {commit[:7]} — {r['note']}")
        elif r["disposition"] == "reverted":
            lines.append(f"{r['id']}: fixed in {commit[:7]} by withdrawing the glow-up's edit "
                         f"(master's text restored) — {r['note']}")
        elif r["disposition"] == "refuted":
            lines.append(f"{r['id']}: this is wrong — {r['note']} Source: {r['source']}")
    if not lines:
        return ""
    body = [f"<!-- {PASS_MARKER} pass={sel.get('pass')} head={commit} -->",
            "@claude answering for the glow-up automation (pass "
            f"{sel.get('pass')} of {MAX_PASSES}):", ""]
    body += [f"- {ln}" for ln in lines]
    body += ["", "#update-review"]
    return "\n".join(body) + FOOTER


def render_pass_marker_only(sel: dict, commit: str, rows: list[dict]) -> str:
    """A pass that recorded nothing still has to count against the budget."""
    ids = ", ".join(r["id"] for r in rows) or "none"
    return (f"<!-- {PASS_MARKER} pass={sel.get('pass')} head={commit} -->\n"
            f"Glow-up autofix pass {sel.get('pass')} of {MAX_PASSES} could not settle any open finding "
            f"({ids}); they are for the requested reviewer." + FOOTER)


def render_section(history: list[dict]) -> str:
    out = [f"## {SECTION}", "",
           "What the automated pass did with each blocking finding the pre-merge review raised "
           "after this PR opened. Anything `unresolved` was handed to the routed reviewer.", "",
           "| Pass | ID | Finding | Disposition | Note / source |", "| --- | --- | --- | --- | --- |"]
    for h in history:
        for r in h.get("rows") or []:
            ns = r.get("note", "")
            if r.get("source"):
                ns += f" Source: {r['source']}"
            out.append(f"| {h.get('pass')} ({(h.get('commit') or '')[:7]}) | {r['id']} | {_cell(r.get('summary'), 160)} | "
                       f"{r.get('disposition')} | {_cell(ns, 240)} |")
    return "\n".join(out) + "\n"


def splice_section(body: str, section_md: str) -> str:
    pat = re.compile(rf"^##\s+{re.escape(SECTION)}\s*$.*?(?=^##\s|\Z)", re.M | re.S)
    if pat.search(body or ""):
        return pat.sub(lambda _m: section_md.rstrip() + "\n\n", body, count=1)
    m = re.search(r"^##\s+Screenshot check\s*$", body or "", re.M)
    if m:
        return body[: m.start()] + section_md.rstrip() + "\n\n" + body[m.start():]
    return (body or "").rstrip() + "\n\n" + section_md


def history_from_body(body: str) -> list[dict]:
    """Earlier passes' rows, read back from the body's own section, so the
    section accumulates across passes without any state outside the PR."""
    m = re.search(rf"^##\s+{re.escape(SECTION)}\s*$(.*?)(?=^##\s|\Z)", body or "", re.M | re.S)
    if not m:
        return []
    passes: dict[str, dict] = {}
    for line in m.group(1).splitlines():
        cells = [c.strip() for c in re.split(r"(?<!\\)\|", line.strip())[1:-1]]
        if len(cells) != 5 or not re.match(r"^\d+ \(", cells[0]):
            continue
        pm = re.match(r"^(\d+) \(([0-9a-f]*)\)", cells[0])
        key = pm.group(1)
        h = passes.setdefault(key, {"pass": int(key), "commit": pm.group(2), "rows": []})
        h["rows"].append({"id": cells[1], "summary": cells[2].replace("\\|", "|"),
                          "disposition": cells[3], "note": cells[4].replace("\\|", "|"), "source": ""})
    return [passes[k] for k in sorted(passes, key=int)]


def render_escalation(sel: dict, rows: list[dict], teams: list[str]) -> str:
    who = " ".join(f"@{t}" for t in teams) or "the routed reviewer"
    open_rows = [r for r in rows if r["disposition"] == "unresolved"] or \
        [{"id": f["id"], "summary": f.get("summary", ""), "note": ""} for f in sel.get("open") or []]
    lines = [f"<!-- {ESCALATED_MARKER} head={sel.get('head_sha', '')[:7]} -->",
             f"{who}: this glow-up couldn't reach a clean review automatically, so these are yours "
             "to decide (fix, refute, or accept on the review card):", ""]
    for r in open_rows:
        tail = f" _(automation: {r['note']})_" if r.get("note") else ""
        lines.append(f"- **{r['id']}** — {_cell(r.get('summary'), 240)}{tail}")
    lines += ["", "Pre-verification receipts and every automated disposition are in the PR body."]
    return "\n".join(lines) + FOOTER


def cmd_select(a) -> int:
    pr = json.loads(Path(a.pr_json).read_text())
    wl = json.loads(Path(a.worklist).read_text()) if Path(a.worklist).exists() else {}
    comments = json.loads(Path(a.comments).read_text()) if Path(a.comments).exists() else []
    res = select(pr, wl, comments, a.max_passes)
    print(json.dumps(res, indent=2))
    print(f"glowup-autofix select #{res.get('pr')}: {res['action']} — {res['reason']}", file=sys.stderr)
    return 0


def cmd_answer(a) -> int:
    sel = json.loads(Path(a.select).read_text())
    disp = {}
    if a.dispositions and Path(a.dispositions).exists():
        try:
            disp = json.loads(Path(a.dispositions).read_text())
        except json.JSONDecodeError:
            disp = {}
    post = json.loads(Path(a.postcheck).read_text()) if a.postcheck and Path(a.postcheck).exists() else None
    rows = fold(sel, disp, post)
    od = Path(a.out_dir)
    od.mkdir(parents=True, exist_ok=True)
    answer = render_answer(rows, sel, a.commit)
    (od / "answer.md").write_text(answer or render_pass_marker_only(sel, a.commit, rows))
    body = Path(a.body).read_text() if a.body and Path(a.body).exists() else ""
    history = [h for h in history_from_body(body) if h["pass"] != sel.get("pass")]
    history.append({"pass": sel.get("pass"), "commit": a.commit, "rows": rows})
    (od / "body.md").write_text(splice_section(body, render_section(history)))
    unresolved = [r["id"] for r in rows if r["disposition"] == "unresolved"]
    escalate = bool(unresolved) or int(sel.get("pass") or 0) >= MAX_PASSES
    (od / "rows.json").write_text(json.dumps({"rows": rows, "unresolved": unresolved,
                                              "escalate": escalate}, indent=2) + "\n")
    teams = [t for t in (a.teams or "").split() if t]
    (od / "escalation.md").write_text(render_escalation(sel, rows, teams))
    print(f"glowup-autofix answer: {len(rows)} finding(s); unresolved={unresolved}; escalate={escalate}",
          file=sys.stderr)
    return 0


def cmd_escalation(a) -> int:
    sel = json.loads(Path(a.select).read_text())
    teams = [t for t in (a.teams or "").split() if t]
    Path(a.out).write_text(render_escalation(sel, [], teams))
    return 0


def self_test() -> int:
    fails = []

    def check(c, msg):
        if not c:
            fails.append(msg)

    head = "e395169ab30e414893edf061d22d7fecab45555a"
    pr = {"number": 1, "headRefOid": head, "headRefName": "content-review/glowup-docs-x",
          "author": {"login": BOT}, "state": "OPEN", "isDraft": False,
          "files": [{"path": "content/docs/x.md"}]}
    wl = {"surface": "v3", "parse_confidence": "high", "reviewed_sha": head, "items": [
        {"id": "F1", "bucket": "outstanding", "anchor": "L10", "blocking": True, "disposition": None,
         "summary": "four properties"},
        {"id": "F2", "bucket": "author-answer", "anchor": "L40-41", "blocking": True, "disposition": None,
         "summary": "unverified shorthand"},
        {"id": "F3", "bucket": "outstanding", "anchor": "L50", "blocking": True, "disposition": "fixed"},
        {"id": "S1", "bucket": "style", "blocking": False, "disposition": None}]}
    s = select(pr, wl, [])
    check(s["action"] == "fix" and s["pass"] == 1 and [o["id"] for o in s["open"]] == ["F1", "F2"],
          f"select fix {s}")
    check(select({**pr, "author": {"login": "someone"}}, wl, [])["action"] == "none", "human PR ignored")
    check(select({**pr, "headRefName": "content-review/docs-x"}, wl, [])["action"] == "none",
          "fix-lane PR ignored")
    check(select(pr, {**wl, "reviewed_sha": "abcdef1"}, [])["action"] == "none", "stale card waits")
    check(select(pr, {**wl, "items": wl["items"][2:]}, [])["action"] == "none", "nothing open")
    c1 = [{"user": {"login": BOT}, "body": f"<!-- {PASS_MARKER} pass=1 head={head[:7]} -->"}]
    check(select(pr, wl, c1)["action"] == "none", "same head never gets a second pass")
    c2 = [{"user": {"login": BOT}, "body": f"<!-- {PASS_MARKER} pass=1 head=1111111 -->"}]
    check(select(pr, wl, c2)["pass"] == 2, "second pass on a new head")
    c3 = c2 + [{"user": {"login": BOT}, "body": f"<!-- {PASS_MARKER} pass=2 head=2222222 -->"}]
    check(select(pr, wl, c3)["action"] == "escalate", "budget spent escalates")
    c4 = c3 + [{"user": {"login": BOT}, "body": f"<!-- {ESCALATED_MARKER} head=2222222 -->"}]
    check(select(pr, wl, c4)["action"] == "none", "escalates once")
    forged = [{"user": {"login": "mallory"}, "body": f"<!-- {PASS_MARKER} pass=9 head=1111111 -->"}]
    check(select(pr, wl, forged)["pass"] == 1, "markers from other users don't count")

    disp = {"findings": [
        {"id": "F1", "disposition": "fixed", "note": "Dropped the count; the source declares five."},
        {"id": "F2", "disposition": "refuted", "note": "It is documented."}]}
    rows = fold(s, disp, None)
    check(rows[0]["disposition"] == "fixed", "fixed kept")
    check(rows[1]["disposition"] == "unresolved" and "no source" in rows[1]["note"], "refute needs a source")
    rows = fold(s, {"findings": [{"id": "F1", "disposition": "accepted", "note": "x"}]}, None)
    check(all(r["disposition"] == "unresolved" for r in rows), "bot cannot accept; missing is unresolved")
    post = {"blocks": [{"pristine_lines": [9, 11]}]}
    rows = fold(s, disp, post)
    check(rows[0]["disposition"] == "unresolved" and "re-verify" in rows[0]["note"],
          "post-check revert overrides fixed")

    rows = fold(s, {"findings": [
        {"id": "F1", "disposition": "reverted", "note": "Withdrew the count change."},
        {"id": "F2", "disposition": "refuted", "note": "Documented.", "source": "pulumi-yaml/pkg/x.go"}]}, None)
    ans = render_answer(rows, s, head)
    check(ans.startswith(f"<!-- {PASS_MARKER} pass=1 head={head} -->"), "answer carries marker")
    check("@claude" in ans and "#update-review" in ans and "F1: fixed in e395169" in ans
          and "Source: pulumi-yaml" in ans, "answer shape")
    check(ans.rstrip().endswith("_Generated by [Claude Code](https://claude.ai/code)_"), "footer")
    check(render_answer([{**rows[0], "disposition": "unresolved"}], s, head) == "", "nothing to record")

    sec = render_section([{"pass": 1, "commit": head, "rows": rows}])
    body = splice_section("## Why this page\n\nx\n\n## Screenshot check\n\ny\n", sec)
    hist = history_from_body(body)
    check(len(hist) == 1 and hist[0]["rows"][1]["id"] == "F2", f"history round-trips {hist}")
    body2 = splice_section(body, render_section(hist + [{"pass": 2, "commit": "f" * 40, "rows": rows[:1]}]))
    check(body2.count(f"## {SECTION}") == 1 and len(history_from_body(body2)) == 2, "section accumulates")
    esc = render_escalation(s, [{**rows[0], "disposition": "unresolved", "note": "x"}], ["pulumi/docs-guild"])
    check("@pulumi/docs-guild" in esc and ESCALATED_MARKER in esc and "**F1**" in esc, "escalation")

    if fails:
        for f in fails:
            print(f"FAIL: {f}", file=sys.stderr)
        return 1
    print("glowup-autofix self-test: ok", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv[:1] == ["--self-test"]:
        return self_test()
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--self-test", action="store_true")
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("select")
    s.add_argument("--pr-json", required=True)
    s.add_argument("--worklist", required=True)
    s.add_argument("--comments", required=True)
    s.add_argument("--max-passes", type=int, default=MAX_PASSES)
    an = sub.add_parser("answer")
    an.add_argument("--select", required=True)
    an.add_argument("--dispositions")
    an.add_argument("--postcheck")
    an.add_argument("--commit", required=True)
    an.add_argument("--body", help="current PR body (the section accumulates across passes)")
    an.add_argument("--teams", default="", help="space-separated routed teams (org/slug)")
    an.add_argument("--out-dir", required=True)
    e = sub.add_parser("escalation")
    e.add_argument("--select", required=True)
    e.add_argument("--teams", default="")
    e.add_argument("--out", required=True)
    a = p.parse_args(argv)
    return {"select": cmd_select, "answer": cmd_answer, "escalation": cmd_escalation}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
