/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { APINavNode } from "./components/pulumi-api-doc-filterable-nav/pulumi-api-doc-filterable-nav";
import { ChooserKey, ChooserMode, ChooserType, OSKey } from "./components/chooser/chooser";
import { ChooserKey as ChooserKey1, ChooserMode as ChooserMode1, ChooserOptionStyle, ChooserType as ChooserType1 } from "./components/chooser/chooser";
import { SourceKind } from "./components/convert/convert";
import { Filter } from "./components/filter-select/filter-select-option";
import { MultiSelectFormItem } from "./components/pulumi-multi-select-form/pulumi-multi-select-form";
export { APINavNode } from "./components/pulumi-api-doc-filterable-nav/pulumi-api-doc-filterable-nav";
export { ChooserKey, ChooserMode, ChooserType, OSKey } from "./components/chooser/chooser";
export { ChooserKey as ChooserKey1, ChooserMode as ChooserMode1, ChooserOptionStyle, ChooserType as ChooserType1 } from "./components/chooser/chooser";
export { SourceKind } from "./components/convert/convert";
export { Filter } from "./components/filter-select/filter-select-option";
export { MultiSelectFormItem } from "./components/pulumi-multi-select-form/pulumi-multi-select-form";
export namespace Components {
    interface CopilotSidebar {
        "atlasUrl": string;
    }
    interface EventSessionRegistrationModal {
        "buttonClass": string;
        "buttonText": string;
        "eventSessions": string;
        "modalTitle": string;
        /**
          * @default "/pulumi-up/thank-you/"
         */
        "redirectUrl": string;
    }
    interface HeaderCta {
        /**
          * @default ""
         */
        "buttonClass": string;
        /**
          * @default "https://app.pulumi.com/signup"
         */
        "href": string;
        /**
          * @default "Sign Up"
         */
        "label": string;
    }
    interface HomeSlots {
        /**
          * @default ""
         */
        "centerItems": string;
        /**
          * @default ""
         */
        "imageClass": string;
        /**
          * @default ""
         */
        "leftItems": string;
        /**
          * @default ""
         */
        "rightItems": string;
    }
    interface PricingCta {
        /**
          * @default ""
         */
        "buttonClass": string;
        "signedInText": string;
        "signedOutText": string;
    }
    interface PulumiApiDocFilterableNav {
        "baseDirectory": string;
        "packageName": string;
    }
    interface PulumiApiDocNavNode {
        /**
          * @default 0
         */
        "depth": number;
        "href": string;
        "isExpanded": boolean;
        "node": APINavNode;
    }
    interface PulumiApiDocNavTree {
        "baseDirectory": string;
        "nodes": APINavNode[];
    }
    interface PulumiAudio {
        "pausedText": string;
        "playingText": string;
        "url": string;
    }
    interface PulumiBanner {
        /**
          * @default true
         */
        "dismissible": boolean;
        "name": string;
        /**
          * @default false
         */
        "visible": boolean;
    }
    /**
     * The Choosable component is useful for showing or hiding information based on the
     * currently selected ChooserType and value. For example, a component defined as:
     *     <pulumi-choosable type="language" value="typescript">
     *         I <3 TypeScript.
     *     </pulumi-choosable>
     * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
     * selected language choice is TypeScript.
     */
    interface PulumiChoosable {
        "mode": ChooserMode;
        "selection": ChooserKey;
        "type": ChooserType;
        "value": ChooserKey;
        "values": ChooserKey;
    }
    /**
     * The Chooser component renders a set of selectable tabs based on the type and options
     * properties provided. For example, this definition:
     *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
     * ...would render three tabs. Clicking a tab dispatches an action that sets the
     * associated value on the store, allowing any pulumi-choosable component on the page to
     * be shown or hidden automatically.
     * Alternatively, you can provide one or more pulumi-choosable components as children of
     * this component, which will have the effect of treating them as tabbed content,
     * irrespective of what may or may not be set on the global store. For example:
     *     <pulumi-chooser type="language" value="typescript,javascript">
     *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
     *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
     *     </pulumi-chooser>
     */
    interface PulumiChooser {
        "mode": ChooserMode1;
        "optionStyle": ChooserOptionStyle;
        "options": string;
        "selection": ChooserKey1;
        "type": ChooserType1;
    }
    interface PulumiContactUsForm {
        "items": string;
        "labelClass"?: string;
        "selectClass"?: string;
    }
    interface PulumiConvert {
        "endpoint": string;
        "examples": string;
        "from": SourceKind;
        /**
          * @default ""
         */
        "theme": string;
    }
    interface PulumiDateCountdown {
        /**
          * @default ""
         */
        "containerClass": string;
        /**
          * @default ""
         */
        "countdownOverText": string;
        "dateString": string;
        /**
          * @default ""
         */
        "textClass": string;
        /**
          * @default ""
         */
        "valueLabelClass": string;
    }
    interface PulumiDateCountdownCircles {
        /**
          * @default ""
         */
        "containerClass": string;
        "dateString": string;
        /**
          * @default ""
         */
        "valueLabelClass": string;
    }
    interface PulumiDatetime {
        "class"?: string;
        "date": string;
        "timeonly"?: boolean;
    }
    interface PulumiDeveloperQuotes {
        "quotes": string;
    }
    interface PulumiDocsNav {
        /**
          * @default ""
         */
        "expandedMenuIDs": string;
    }
    interface PulumiExample {
    }
    interface PulumiExamples {
    }
    interface PulumiFilterSelect {
        "deselect": (filter: Filter) => Promise<void>;
        "reset": () => Promise<any>;
        "select": (filter: Filter) => Promise<void>;
    }
    interface PulumiFilterSelectOption {
        "deselect": () => Promise<void>;
        "label"?: string;
        "select": () => Promise<void>;
        "selected": boolean;
        "value": string;
    }
    interface PulumiFilterSelectOptionGroup {
        "close": () => Promise<any>;
        "expanded": boolean;
        "name": string;
    }
    interface PulumiGreenhouseJobsList {
    }
    interface PulumiHubspotForm {
        "class"?: string;
        "formId": string;
        "goToWebinarKey"?: string;
        "salesforceCampaignId": string;
    }
    interface PulumiInstall {
        "os"?: OSKey;
    }
    interface PulumiLlmMenu {
        "pageTitle": string;
        "pageUrl": string;
    }
    interface PulumiMultiSelectForm {
        /**
          * @default ""
         */
        "defaultFormId": string;
        /**
          * @default []
         */
        "items": MultiSelectFormItem[];
        "labelClass"?: string;
        "labelText": string;
        "selectClass"?: string;
    }
    interface PulumiPricingCalculator {
    }
    interface PulumiRegistryListSearch {
    }
    interface PulumiResourceLinks {
        "moduleName": string;
        "packageName": string;
        "resourceName": string;
    }
    interface PulumiRoot {
    }
    interface PulumiSlotMachine {
        "centerImages": string;
        "imageClass": string;
        "leftImages": string;
        "rightImages": string;
    }
    interface PulumiSwipeable {
    }
    interface PulumiSwiper {
        /**
          * @default false
         */
        "autoplay": boolean;
        /**
          * @default 3000
         */
        "autoplayDelay": number;
        /**
          * @default false
         */
        "centeredSlides": boolean;
        /**
          * @default "horizontal"
         */
        "direction": "vertical" | "horizontal";
        /**
          * @default true
         */
        "enableMouseEvents": boolean;
        /**
          * @default 1
         */
        "initialSlide": number;
        /**
          * @default false
         */
        "loop": boolean;
        /**
          * @default false
         */
        "navControls": boolean;
        /**
          * @default 1
         */
        "slides": number;
        /**
          * @default 0
         */
        "spaceBetween": number;
        /**
          * @default 300
         */
        "speed": number;
        "startSwiper": () => Promise<void>;
        "stopSwiper": () => Promise<void>;
    }
    interface PulumiTab {
        "active": boolean;
        "label": string;
    }
    interface PulumiTabs {
    }
    interface PulumiTertiaryNav {
        "items": string;
        "selection": any;
        "tabContent": string[];
    }
    /**
     * The ToolTip component shows a tooltip bubble above another element when you hover over
     * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
     * show in the bubble.
     * Usage:
     * <pulumi-tooltip>
     *     <i class="fas fa-question-circle"></i>
     *     <span slot="content">
     *         You hovered over (or tapped on) the thing!
     *     </span>
     * </pulumi-tooltip>
     */
    interface PulumiTooltip {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
    }
    interface PulumiTopButton {
    }
    interface PulumiUserToggle {
        "userId": string;
    }
    interface PulumiValueCalculator {
    }
    interface PulumiWebinarFormSelect {
        "labelClass"?: string;
        "selectClass"?: string;
        "sessions": string;
    }
}
export interface PulumiFilterSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiFilterSelectElement;
}
export interface PulumiFilterSelectOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiFilterSelectOptionElement;
}
export interface PulumiRegistryListSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiRegistryListSearchElement;
}
export interface PulumiRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiRootElement;
}
export interface PulumiTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiTabsElement;
}
declare global {
    interface HTMLCopilotSidebarElement extends Components.CopilotSidebar, HTMLStencilElement {
    }
    var HTMLCopilotSidebarElement: {
        prototype: HTMLCopilotSidebarElement;
        new (): HTMLCopilotSidebarElement;
    };
    interface HTMLEventSessionRegistrationModalElement extends Components.EventSessionRegistrationModal, HTMLStencilElement {
    }
    var HTMLEventSessionRegistrationModalElement: {
        prototype: HTMLEventSessionRegistrationModalElement;
        new (): HTMLEventSessionRegistrationModalElement;
    };
    interface HTMLHeaderCtaElement extends Components.HeaderCta, HTMLStencilElement {
    }
    var HTMLHeaderCtaElement: {
        prototype: HTMLHeaderCtaElement;
        new (): HTMLHeaderCtaElement;
    };
    interface HTMLHomeSlotsElement extends Components.HomeSlots, HTMLStencilElement {
    }
    var HTMLHomeSlotsElement: {
        prototype: HTMLHomeSlotsElement;
        new (): HTMLHomeSlotsElement;
    };
    interface HTMLPricingCtaElement extends Components.PricingCta, HTMLStencilElement {
    }
    var HTMLPricingCtaElement: {
        prototype: HTMLPricingCtaElement;
        new (): HTMLPricingCtaElement;
    };
    interface HTMLPulumiApiDocFilterableNavElement extends Components.PulumiApiDocFilterableNav, HTMLStencilElement {
    }
    var HTMLPulumiApiDocFilterableNavElement: {
        prototype: HTMLPulumiApiDocFilterableNavElement;
        new (): HTMLPulumiApiDocFilterableNavElement;
    };
    interface HTMLPulumiApiDocNavNodeElement extends Components.PulumiApiDocNavNode, HTMLStencilElement {
    }
    var HTMLPulumiApiDocNavNodeElement: {
        prototype: HTMLPulumiApiDocNavNodeElement;
        new (): HTMLPulumiApiDocNavNodeElement;
    };
    interface HTMLPulumiApiDocNavTreeElement extends Components.PulumiApiDocNavTree, HTMLStencilElement {
    }
    var HTMLPulumiApiDocNavTreeElement: {
        prototype: HTMLPulumiApiDocNavTreeElement;
        new (): HTMLPulumiApiDocNavTreeElement;
    };
    interface HTMLPulumiAudioElement extends Components.PulumiAudio, HTMLStencilElement {
    }
    var HTMLPulumiAudioElement: {
        prototype: HTMLPulumiAudioElement;
        new (): HTMLPulumiAudioElement;
    };
    interface HTMLPulumiBannerElement extends Components.PulumiBanner, HTMLStencilElement {
    }
    var HTMLPulumiBannerElement: {
        prototype: HTMLPulumiBannerElement;
        new (): HTMLPulumiBannerElement;
    };
    /**
     * The Choosable component is useful for showing or hiding information based on the
     * currently selected ChooserType and value. For example, a component defined as:
     *     <pulumi-choosable type="language" value="typescript">
     *         I <3 TypeScript.
     *     </pulumi-choosable>
     * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
     * selected language choice is TypeScript.
     */
    interface HTMLPulumiChoosableElement extends Components.PulumiChoosable, HTMLStencilElement {
    }
    var HTMLPulumiChoosableElement: {
        prototype: HTMLPulumiChoosableElement;
        new (): HTMLPulumiChoosableElement;
    };
    /**
     * The Chooser component renders a set of selectable tabs based on the type and options
     * properties provided. For example, this definition:
     *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
     * ...would render three tabs. Clicking a tab dispatches an action that sets the
     * associated value on the store, allowing any pulumi-choosable component on the page to
     * be shown or hidden automatically.
     * Alternatively, you can provide one or more pulumi-choosable components as children of
     * this component, which will have the effect of treating them as tabbed content,
     * irrespective of what may or may not be set on the global store. For example:
     *     <pulumi-chooser type="language" value="typescript,javascript">
     *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
     *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
     *     </pulumi-chooser>
     */
    interface HTMLPulumiChooserElement extends Components.PulumiChooser, HTMLStencilElement {
    }
    var HTMLPulumiChooserElement: {
        prototype: HTMLPulumiChooserElement;
        new (): HTMLPulumiChooserElement;
    };
    interface HTMLPulumiContactUsFormElement extends Components.PulumiContactUsForm, HTMLStencilElement {
    }
    var HTMLPulumiContactUsFormElement: {
        prototype: HTMLPulumiContactUsFormElement;
        new (): HTMLPulumiContactUsFormElement;
    };
    interface HTMLPulumiConvertElement extends Components.PulumiConvert, HTMLStencilElement {
    }
    var HTMLPulumiConvertElement: {
        prototype: HTMLPulumiConvertElement;
        new (): HTMLPulumiConvertElement;
    };
    interface HTMLPulumiDateCountdownElement extends Components.PulumiDateCountdown, HTMLStencilElement {
    }
    var HTMLPulumiDateCountdownElement: {
        prototype: HTMLPulumiDateCountdownElement;
        new (): HTMLPulumiDateCountdownElement;
    };
    interface HTMLPulumiDateCountdownCirclesElement extends Components.PulumiDateCountdownCircles, HTMLStencilElement {
    }
    var HTMLPulumiDateCountdownCirclesElement: {
        prototype: HTMLPulumiDateCountdownCirclesElement;
        new (): HTMLPulumiDateCountdownCirclesElement;
    };
    interface HTMLPulumiDatetimeElement extends Components.PulumiDatetime, HTMLStencilElement {
    }
    var HTMLPulumiDatetimeElement: {
        prototype: HTMLPulumiDatetimeElement;
        new (): HTMLPulumiDatetimeElement;
    };
    interface HTMLPulumiDeveloperQuotesElement extends Components.PulumiDeveloperQuotes, HTMLStencilElement {
    }
    var HTMLPulumiDeveloperQuotesElement: {
        prototype: HTMLPulumiDeveloperQuotesElement;
        new (): HTMLPulumiDeveloperQuotesElement;
    };
    interface HTMLPulumiDocsNavElement extends Components.PulumiDocsNav, HTMLStencilElement {
    }
    var HTMLPulumiDocsNavElement: {
        prototype: HTMLPulumiDocsNavElement;
        new (): HTMLPulumiDocsNavElement;
    };
    interface HTMLPulumiExampleElement extends Components.PulumiExample, HTMLStencilElement {
    }
    var HTMLPulumiExampleElement: {
        prototype: HTMLPulumiExampleElement;
        new (): HTMLPulumiExampleElement;
    };
    interface HTMLPulumiExamplesElement extends Components.PulumiExamples, HTMLStencilElement {
    }
    var HTMLPulumiExamplesElement: {
        prototype: HTMLPulumiExamplesElement;
        new (): HTMLPulumiExamplesElement;
    };
    interface HTMLPulumiFilterSelectElementEventMap {
        "filterSelect": any[];
    }
    interface HTMLPulumiFilterSelectElement extends Components.PulumiFilterSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiFilterSelectElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectElement, ev: PulumiFilterSelectCustomEvent<HTMLPulumiFilterSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiFilterSelectElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectElement, ev: PulumiFilterSelectCustomEvent<HTMLPulumiFilterSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiFilterSelectElement: {
        prototype: HTMLPulumiFilterSelectElement;
        new (): HTMLPulumiFilterSelectElement;
    };
    interface HTMLPulumiFilterSelectOptionElementEventMap {
        "optionChange": any;
    }
    interface HTMLPulumiFilterSelectOptionElement extends Components.PulumiFilterSelectOption, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiFilterSelectOptionElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectOptionElement, ev: PulumiFilterSelectOptionCustomEvent<HTMLPulumiFilterSelectOptionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiFilterSelectOptionElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectOptionElement, ev: PulumiFilterSelectOptionCustomEvent<HTMLPulumiFilterSelectOptionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiFilterSelectOptionElement: {
        prototype: HTMLPulumiFilterSelectOptionElement;
        new (): HTMLPulumiFilterSelectOptionElement;
    };
    interface HTMLPulumiFilterSelectOptionGroupElement extends Components.PulumiFilterSelectOptionGroup, HTMLStencilElement {
    }
    var HTMLPulumiFilterSelectOptionGroupElement: {
        prototype: HTMLPulumiFilterSelectOptionGroupElement;
        new (): HTMLPulumiFilterSelectOptionGroupElement;
    };
    interface HTMLPulumiGreenhouseJobsListElement extends Components.PulumiGreenhouseJobsList, HTMLStencilElement {
    }
    var HTMLPulumiGreenhouseJobsListElement: {
        prototype: HTMLPulumiGreenhouseJobsListElement;
        new (): HTMLPulumiGreenhouseJobsListElement;
    };
    interface HTMLPulumiHubspotFormElement extends Components.PulumiHubspotForm, HTMLStencilElement {
    }
    var HTMLPulumiHubspotFormElement: {
        prototype: HTMLPulumiHubspotFormElement;
        new (): HTMLPulumiHubspotFormElement;
    };
    interface HTMLPulumiInstallElement extends Components.PulumiInstall, HTMLStencilElement {
    }
    var HTMLPulumiInstallElement: {
        prototype: HTMLPulumiInstallElement;
        new (): HTMLPulumiInstallElement;
    };
    interface HTMLPulumiLlmMenuElement extends Components.PulumiLlmMenu, HTMLStencilElement {
    }
    var HTMLPulumiLlmMenuElement: {
        prototype: HTMLPulumiLlmMenuElement;
        new (): HTMLPulumiLlmMenuElement;
    };
    interface HTMLPulumiMultiSelectFormElement extends Components.PulumiMultiSelectForm, HTMLStencilElement {
    }
    var HTMLPulumiMultiSelectFormElement: {
        prototype: HTMLPulumiMultiSelectFormElement;
        new (): HTMLPulumiMultiSelectFormElement;
    };
    interface HTMLPulumiPricingCalculatorElement extends Components.PulumiPricingCalculator, HTMLStencilElement {
    }
    var HTMLPulumiPricingCalculatorElement: {
        prototype: HTMLPulumiPricingCalculatorElement;
        new (): HTMLPulumiPricingCalculatorElement;
    };
    interface HTMLPulumiRegistryListSearchElementEventMap {
        "packageSearch": string;
    }
    interface HTMLPulumiRegistryListSearchElement extends Components.PulumiRegistryListSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiRegistryListSearchElementEventMap>(type: K, listener: (this: HTMLPulumiRegistryListSearchElement, ev: PulumiRegistryListSearchCustomEvent<HTMLPulumiRegistryListSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiRegistryListSearchElementEventMap>(type: K, listener: (this: HTMLPulumiRegistryListSearchElement, ev: PulumiRegistryListSearchCustomEvent<HTMLPulumiRegistryListSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiRegistryListSearchElement: {
        prototype: HTMLPulumiRegistryListSearchElement;
        new (): HTMLPulumiRegistryListSearchElement;
    };
    interface HTMLPulumiResourceLinksElement extends Components.PulumiResourceLinks, HTMLStencilElement {
    }
    var HTMLPulumiResourceLinksElement: {
        prototype: HTMLPulumiResourceLinksElement;
        new (): HTMLPulumiResourceLinksElement;
    };
    interface HTMLPulumiRootElementEventMap {
        "rendered": any;
    }
    interface HTMLPulumiRootElement extends Components.PulumiRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiRootElementEventMap>(type: K, listener: (this: HTMLPulumiRootElement, ev: PulumiRootCustomEvent<HTMLPulumiRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiRootElementEventMap>(type: K, listener: (this: HTMLPulumiRootElement, ev: PulumiRootCustomEvent<HTMLPulumiRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiRootElement: {
        prototype: HTMLPulumiRootElement;
        new (): HTMLPulumiRootElement;
    };
    interface HTMLPulumiSlotMachineElement extends Components.PulumiSlotMachine, HTMLStencilElement {
    }
    var HTMLPulumiSlotMachineElement: {
        prototype: HTMLPulumiSlotMachineElement;
        new (): HTMLPulumiSlotMachineElement;
    };
    interface HTMLPulumiSwipeableElement extends Components.PulumiSwipeable, HTMLStencilElement {
    }
    var HTMLPulumiSwipeableElement: {
        prototype: HTMLPulumiSwipeableElement;
        new (): HTMLPulumiSwipeableElement;
    };
    interface HTMLPulumiSwiperElement extends Components.PulumiSwiper, HTMLStencilElement {
    }
    var HTMLPulumiSwiperElement: {
        prototype: HTMLPulumiSwiperElement;
        new (): HTMLPulumiSwiperElement;
    };
    interface HTMLPulumiTabElement extends Components.PulumiTab, HTMLStencilElement {
    }
    var HTMLPulumiTabElement: {
        prototype: HTMLPulumiTabElement;
        new (): HTMLPulumiTabElement;
    };
    interface HTMLPulumiTabsElementEventMap {
        "tabSelect": any[];
    }
    interface HTMLPulumiTabsElement extends Components.PulumiTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiTabsElementEventMap>(type: K, listener: (this: HTMLPulumiTabsElement, ev: PulumiTabsCustomEvent<HTMLPulumiTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiTabsElementEventMap>(type: K, listener: (this: HTMLPulumiTabsElement, ev: PulumiTabsCustomEvent<HTMLPulumiTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiTabsElement: {
        prototype: HTMLPulumiTabsElement;
        new (): HTMLPulumiTabsElement;
    };
    interface HTMLPulumiTertiaryNavElement extends Components.PulumiTertiaryNav, HTMLStencilElement {
    }
    var HTMLPulumiTertiaryNavElement: {
        prototype: HTMLPulumiTertiaryNavElement;
        new (): HTMLPulumiTertiaryNavElement;
    };
    /**
     * The ToolTip component shows a tooltip bubble above another element when you hover over
     * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
     * show in the bubble.
     * Usage:
     * <pulumi-tooltip>
     *     <i class="fas fa-question-circle"></i>
     *     <span slot="content">
     *         You hovered over (or tapped on) the thing!
     *     </span>
     * </pulumi-tooltip>
     */
    interface HTMLPulumiTooltipElement extends Components.PulumiTooltip, HTMLStencilElement {
    }
    var HTMLPulumiTooltipElement: {
        prototype: HTMLPulumiTooltipElement;
        new (): HTMLPulumiTooltipElement;
    };
    interface HTMLPulumiTopButtonElement extends Components.PulumiTopButton, HTMLStencilElement {
    }
    var HTMLPulumiTopButtonElement: {
        prototype: HTMLPulumiTopButtonElement;
        new (): HTMLPulumiTopButtonElement;
    };
    interface HTMLPulumiUserToggleElement extends Components.PulumiUserToggle, HTMLStencilElement {
    }
    var HTMLPulumiUserToggleElement: {
        prototype: HTMLPulumiUserToggleElement;
        new (): HTMLPulumiUserToggleElement;
    };
    interface HTMLPulumiValueCalculatorElement extends Components.PulumiValueCalculator, HTMLStencilElement {
    }
    var HTMLPulumiValueCalculatorElement: {
        prototype: HTMLPulumiValueCalculatorElement;
        new (): HTMLPulumiValueCalculatorElement;
    };
    interface HTMLPulumiWebinarFormSelectElement extends Components.PulumiWebinarFormSelect, HTMLStencilElement {
    }
    var HTMLPulumiWebinarFormSelectElement: {
        prototype: HTMLPulumiWebinarFormSelectElement;
        new (): HTMLPulumiWebinarFormSelectElement;
    };
    interface HTMLElementTagNameMap {
        "copilot-sidebar": HTMLCopilotSidebarElement;
        "event-session-registration-modal": HTMLEventSessionRegistrationModalElement;
        "header-cta": HTMLHeaderCtaElement;
        "home-slots": HTMLHomeSlotsElement;
        "pricing-cta": HTMLPricingCtaElement;
        "pulumi-api-doc-filterable-nav": HTMLPulumiApiDocFilterableNavElement;
        "pulumi-api-doc-nav-node": HTMLPulumiApiDocNavNodeElement;
        "pulumi-api-doc-nav-tree": HTMLPulumiApiDocNavTreeElement;
        "pulumi-audio": HTMLPulumiAudioElement;
        "pulumi-banner": HTMLPulumiBannerElement;
        "pulumi-choosable": HTMLPulumiChoosableElement;
        "pulumi-chooser": HTMLPulumiChooserElement;
        "pulumi-contact-us-form": HTMLPulumiContactUsFormElement;
        "pulumi-convert": HTMLPulumiConvertElement;
        "pulumi-date-countdown": HTMLPulumiDateCountdownElement;
        "pulumi-date-countdown-circles": HTMLPulumiDateCountdownCirclesElement;
        "pulumi-datetime": HTMLPulumiDatetimeElement;
        "pulumi-developer-quotes": HTMLPulumiDeveloperQuotesElement;
        "pulumi-docs-nav": HTMLPulumiDocsNavElement;
        "pulumi-example": HTMLPulumiExampleElement;
        "pulumi-examples": HTMLPulumiExamplesElement;
        "pulumi-filter-select": HTMLPulumiFilterSelectElement;
        "pulumi-filter-select-option": HTMLPulumiFilterSelectOptionElement;
        "pulumi-filter-select-option-group": HTMLPulumiFilterSelectOptionGroupElement;
        "pulumi-greenhouse-jobs-list": HTMLPulumiGreenhouseJobsListElement;
        "pulumi-hubspot-form": HTMLPulumiHubspotFormElement;
        "pulumi-install": HTMLPulumiInstallElement;
        "pulumi-llm-menu": HTMLPulumiLlmMenuElement;
        "pulumi-multi-select-form": HTMLPulumiMultiSelectFormElement;
        "pulumi-pricing-calculator": HTMLPulumiPricingCalculatorElement;
        "pulumi-registry-list-search": HTMLPulumiRegistryListSearchElement;
        "pulumi-resource-links": HTMLPulumiResourceLinksElement;
        "pulumi-root": HTMLPulumiRootElement;
        "pulumi-slot-machine": HTMLPulumiSlotMachineElement;
        "pulumi-swipeable": HTMLPulumiSwipeableElement;
        "pulumi-swiper": HTMLPulumiSwiperElement;
        "pulumi-tab": HTMLPulumiTabElement;
        "pulumi-tabs": HTMLPulumiTabsElement;
        "pulumi-tertiary-nav": HTMLPulumiTertiaryNavElement;
        "pulumi-tooltip": HTMLPulumiTooltipElement;
        "pulumi-top-button": HTMLPulumiTopButtonElement;
        "pulumi-user-toggle": HTMLPulumiUserToggleElement;
        "pulumi-value-calculator": HTMLPulumiValueCalculatorElement;
        "pulumi-webinar-form-select": HTMLPulumiWebinarFormSelectElement;
    }
}
declare namespace LocalJSX {
    interface CopilotSidebar {
        "atlasUrl"?: string;
    }
    interface EventSessionRegistrationModal {
        "buttonClass"?: string;
        "buttonText"?: string;
        "eventSessions"?: string;
        "modalTitle"?: string;
        /**
          * @default "/pulumi-up/thank-you/"
         */
        "redirectUrl"?: string;
    }
    interface HeaderCta {
        /**
          * @default ""
         */
        "buttonClass"?: string;
        /**
          * @default "https://app.pulumi.com/signup"
         */
        "href"?: string;
        /**
          * @default "Sign Up"
         */
        "label"?: string;
    }
    interface HomeSlots {
        /**
          * @default ""
         */
        "centerItems"?: string;
        /**
          * @default ""
         */
        "imageClass"?: string;
        /**
          * @default ""
         */
        "leftItems"?: string;
        /**
          * @default ""
         */
        "rightItems"?: string;
    }
    interface PricingCta {
        /**
          * @default ""
         */
        "buttonClass"?: string;
        "signedInText"?: string;
        "signedOutText"?: string;
    }
    interface PulumiApiDocFilterableNav {
        "baseDirectory"?: string;
        "packageName"?: string;
    }
    interface PulumiApiDocNavNode {
        /**
          * @default 0
         */
        "depth"?: number;
        "href"?: string;
        "isExpanded"?: boolean;
        "node"?: APINavNode;
    }
    interface PulumiApiDocNavTree {
        "baseDirectory"?: string;
        "nodes"?: APINavNode[];
    }
    interface PulumiAudio {
        "pausedText"?: string;
        "playingText"?: string;
        "url"?: string;
    }
    interface PulumiBanner {
        /**
          * @default true
         */
        "dismissible"?: boolean;
        "name"?: string;
        /**
          * @default false
         */
        "visible"?: boolean;
    }
    /**
     * The Choosable component is useful for showing or hiding information based on the
     * currently selected ChooserType and value. For example, a component defined as:
     *     <pulumi-choosable type="language" value="typescript">
     *         I <3 TypeScript.
     *     </pulumi-choosable>
     * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
     * selected language choice is TypeScript.
     */
    interface PulumiChoosable {
        "mode"?: ChooserMode;
        "selection"?: ChooserKey;
        "type"?: ChooserType;
        "value"?: ChooserKey;
        "values"?: ChooserKey;
    }
    /**
     * The Chooser component renders a set of selectable tabs based on the type and options
     * properties provided. For example, this definition:
     *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
     * ...would render three tabs. Clicking a tab dispatches an action that sets the
     * associated value on the store, allowing any pulumi-choosable component on the page to
     * be shown or hidden automatically.
     * Alternatively, you can provide one or more pulumi-choosable components as children of
     * this component, which will have the effect of treating them as tabbed content,
     * irrespective of what may or may not be set on the global store. For example:
     *     <pulumi-chooser type="language" value="typescript,javascript">
     *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
     *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
     *     </pulumi-chooser>
     */
    interface PulumiChooser {
        "mode"?: ChooserMode1;
        "optionStyle"?: ChooserOptionStyle;
        "options"?: string;
        "selection"?: ChooserKey1;
        "type"?: ChooserType1;
    }
    interface PulumiContactUsForm {
        "items"?: string;
        "labelClass"?: string;
        "selectClass"?: string;
    }
    interface PulumiConvert {
        "endpoint"?: string;
        "examples"?: string;
        "from"?: SourceKind;
        /**
          * @default ""
         */
        "theme"?: string;
    }
    interface PulumiDateCountdown {
        /**
          * @default ""
         */
        "containerClass"?: string;
        /**
          * @default ""
         */
        "countdownOverText"?: string;
        "dateString"?: string;
        /**
          * @default ""
         */
        "textClass"?: string;
        /**
          * @default ""
         */
        "valueLabelClass"?: string;
    }
    interface PulumiDateCountdownCircles {
        /**
          * @default ""
         */
        "containerClass"?: string;
        "dateString"?: string;
        /**
          * @default ""
         */
        "valueLabelClass"?: string;
    }
    interface PulumiDatetime {
        "class"?: string;
        "date"?: string;
        "timeonly"?: boolean;
    }
    interface PulumiDeveloperQuotes {
        "quotes"?: string;
    }
    interface PulumiDocsNav {
        /**
          * @default ""
         */
        "expandedMenuIDs"?: string;
    }
    interface PulumiExample {
    }
    interface PulumiExamples {
    }
    interface PulumiFilterSelect {
        "onFilterSelect"?: (event: PulumiFilterSelectCustomEvent<any[]>) => void;
    }
    interface PulumiFilterSelectOption {
        "label"?: string;
        "onOptionChange"?: (event: PulumiFilterSelectOptionCustomEvent<any>) => void;
        "selected"?: boolean;
        "value"?: string;
    }
    interface PulumiFilterSelectOptionGroup {
        "expanded"?: boolean;
        "name"?: string;
    }
    interface PulumiGreenhouseJobsList {
    }
    interface PulumiHubspotForm {
        "class"?: string;
        "formId"?: string;
        "goToWebinarKey"?: string;
        "salesforceCampaignId"?: string;
    }
    interface PulumiInstall {
        "os"?: OSKey;
    }
    interface PulumiLlmMenu {
        "pageTitle"?: string;
        "pageUrl"?: string;
    }
    interface PulumiMultiSelectForm {
        /**
          * @default ""
         */
        "defaultFormId"?: string;
        /**
          * @default []
         */
        "items"?: MultiSelectFormItem[];
        "labelClass"?: string;
        "labelText"?: string;
        "selectClass"?: string;
    }
    interface PulumiPricingCalculator {
    }
    interface PulumiRegistryListSearch {
        "onPackageSearch"?: (event: PulumiRegistryListSearchCustomEvent<string>) => void;
    }
    interface PulumiResourceLinks {
        "moduleName"?: string;
        "packageName"?: string;
        "resourceName"?: string;
    }
    interface PulumiRoot {
        "onRendered"?: (event: PulumiRootCustomEvent<any>) => void;
    }
    interface PulumiSlotMachine {
        "centerImages"?: string;
        "imageClass"?: string;
        "leftImages"?: string;
        "rightImages"?: string;
    }
    interface PulumiSwipeable {
    }
    interface PulumiSwiper {
        /**
          * @default false
         */
        "autoplay"?: boolean;
        /**
          * @default 3000
         */
        "autoplayDelay"?: number;
        /**
          * @default false
         */
        "centeredSlides"?: boolean;
        /**
          * @default "horizontal"
         */
        "direction"?: "vertical" | "horizontal";
        /**
          * @default true
         */
        "enableMouseEvents"?: boolean;
        /**
          * @default 1
         */
        "initialSlide"?: number;
        /**
          * @default false
         */
        "loop"?: boolean;
        /**
          * @default false
         */
        "navControls"?: boolean;
        /**
          * @default 1
         */
        "slides"?: number;
        /**
          * @default 0
         */
        "spaceBetween"?: number;
        /**
          * @default 300
         */
        "speed"?: number;
    }
    interface PulumiTab {
        "active"?: boolean;
        "label"?: string;
    }
    interface PulumiTabs {
        "onTabSelect"?: (event: PulumiTabsCustomEvent<any[]>) => void;
    }
    interface PulumiTertiaryNav {
        "items"?: string;
        "selection"?: any;
        "tabContent"?: string[];
    }
    /**
     * The ToolTip component shows a tooltip bubble above another element when you hover over
     * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
     * show in the bubble.
     * Usage:
     * <pulumi-tooltip>
     *     <i class="fas fa-question-circle"></i>
     *     <span slot="content">
     *         You hovered over (or tapped on) the thing!
     *     </span>
     * </pulumi-tooltip>
     */
    interface PulumiTooltip {
    }
    interface PulumiTopButton {
    }
    interface PulumiUserToggle {
        "userId"?: string;
    }
    interface PulumiValueCalculator {
    }
    interface PulumiWebinarFormSelect {
        "labelClass"?: string;
        "selectClass"?: string;
        "sessions"?: string;
    }

    interface CopilotSidebarAttributes {
        "atlasUrl": string;
    }
    interface EventSessionRegistrationModalAttributes {
        "buttonClass": string;
        "buttonText": string;
        "modalTitle": string;
        "eventSessions": string;
        "redirectUrl": string;
    }
    interface HeaderCtaAttributes {
        "buttonClass": string;
        "href": string;
        "label": string;
    }
    interface HomeSlotsAttributes {
        "leftItems": string;
        "centerItems": string;
        "rightItems": string;
        "imageClass": string;
    }
    interface PricingCtaAttributes {
        "buttonClass": string;
        "signedInText": string;
        "signedOutText": string;
    }
    interface PulumiApiDocFilterableNavAttributes {
        "baseDirectory": string;
        "packageName": string;
    }
    interface PulumiApiDocNavNodeAttributes {
        "href": string;
        "depth": number;
        "isExpanded": boolean;
    }
    interface PulumiApiDocNavTreeAttributes {
        "baseDirectory": string;
    }
    interface PulumiAudioAttributes {
        "url": string;
        "playingText": string;
        "pausedText": string;
    }
    interface PulumiBannerAttributes {
        "name": string;
        "dismissible": boolean;
        "visible": boolean;
    }
    interface PulumiChoosableAttributes {
        "type": ChooserType;
        "value": ChooserKey;
        "values": ChooserKey;
        "mode": ChooserMode;
        "selection": ChooserKey;
    }
    interface PulumiChooserAttributes {
        "type": ChooserType;
        "options": string;
        "selection": ChooserKey;
        "optionStyle": ChooserOptionStyle;
        "mode": ChooserMode;
    }
    interface PulumiContactUsFormAttributes {
        "items": string;
        "selectClass": string;
        "labelClass": string;
    }
    interface PulumiConvertAttributes {
        "from": SourceKind;
        "endpoint": string;
        "examples": string;
        "theme": string;
    }
    interface PulumiDateCountdownAttributes {
        "dateString": string;
        "textClass": string;
        "containerClass": string;
        "valueLabelClass": string;
        "countdownOverText": string;
    }
    interface PulumiDateCountdownCirclesAttributes {
        "dateString": string;
        "containerClass": string;
        "valueLabelClass": string;
    }
    interface PulumiDatetimeAttributes {
        "class": string;
        "timeonly": boolean;
        "date": string;
    }
    interface PulumiDeveloperQuotesAttributes {
        "quotes": string;
    }
    interface PulumiDocsNavAttributes {
        "expandedMenuIDs": string;
    }
    interface PulumiFilterSelectOptionAttributes {
        "label": string;
        "value": string;
        "selected": boolean;
    }
    interface PulumiFilterSelectOptionGroupAttributes {
        "name": string;
        "expanded": boolean;
    }
    interface PulumiHubspotFormAttributes {
        "formId": string;
        "salesforceCampaignId": string;
        "goToWebinarKey": string;
        "class": string;
    }
    interface PulumiInstallAttributes {
        "os": OSKey;
    }
    interface PulumiLlmMenuAttributes {
        "pageUrl": string;
        "pageTitle": string;
    }
    interface PulumiMultiSelectFormAttributes {
        "selectClass": string;
        "labelClass": string;
        "labelText": string;
        "defaultFormId": string;
    }
    interface PulumiResourceLinksAttributes {
        "packageName": string;
        "moduleName": string;
        "resourceName": string;
    }
    interface PulumiSlotMachineAttributes {
        "imageClass": string;
        "leftImages": string;
        "centerImages": string;
        "rightImages": string;
    }
    interface PulumiSwiperAttributes {
        "speed": number;
        "loop": boolean;
        "autoplay": boolean;
        "autoplayDelay": number;
        "navControls": boolean;
        "slides": number;
        "centeredSlides": boolean;
        "initialSlide": number;
        "direction": "vertical" | "horizontal";
        "enableMouseEvents": boolean;
        "spaceBetween": number;
    }
    interface PulumiTabAttributes {
        "label": string;
        "active": boolean;
    }
    interface PulumiTertiaryNavAttributes {
        "items": string;
        "selection": string;
    }
    interface PulumiUserToggleAttributes {
        "userId": string;
    }
    interface PulumiWebinarFormSelectAttributes {
        "sessions": string;
        "selectClass": string;
        "labelClass": string;
    }

    interface IntrinsicElements {
        "copilot-sidebar": Omit<CopilotSidebar, keyof CopilotSidebarAttributes> & { [K in keyof CopilotSidebar & keyof CopilotSidebarAttributes]?: CopilotSidebar[K] } & { [K in keyof CopilotSidebar & keyof CopilotSidebarAttributes as `attr:${K}`]?: CopilotSidebarAttributes[K] } & { [K in keyof CopilotSidebar & keyof CopilotSidebarAttributes as `prop:${K}`]?: CopilotSidebar[K] };
        "event-session-registration-modal": Omit<EventSessionRegistrationModal, keyof EventSessionRegistrationModalAttributes> & { [K in keyof EventSessionRegistrationModal & keyof EventSessionRegistrationModalAttributes]?: EventSessionRegistrationModal[K] } & { [K in keyof EventSessionRegistrationModal & keyof EventSessionRegistrationModalAttributes as `attr:${K}`]?: EventSessionRegistrationModalAttributes[K] } & { [K in keyof EventSessionRegistrationModal & keyof EventSessionRegistrationModalAttributes as `prop:${K}`]?: EventSessionRegistrationModal[K] };
        "header-cta": Omit<HeaderCta, keyof HeaderCtaAttributes> & { [K in keyof HeaderCta & keyof HeaderCtaAttributes]?: HeaderCta[K] } & { [K in keyof HeaderCta & keyof HeaderCtaAttributes as `attr:${K}`]?: HeaderCtaAttributes[K] } & { [K in keyof HeaderCta & keyof HeaderCtaAttributes as `prop:${K}`]?: HeaderCta[K] };
        "home-slots": Omit<HomeSlots, keyof HomeSlotsAttributes> & { [K in keyof HomeSlots & keyof HomeSlotsAttributes]?: HomeSlots[K] } & { [K in keyof HomeSlots & keyof HomeSlotsAttributes as `attr:${K}`]?: HomeSlotsAttributes[K] } & { [K in keyof HomeSlots & keyof HomeSlotsAttributes as `prop:${K}`]?: HomeSlots[K] };
        "pricing-cta": Omit<PricingCta, keyof PricingCtaAttributes> & { [K in keyof PricingCta & keyof PricingCtaAttributes]?: PricingCta[K] } & { [K in keyof PricingCta & keyof PricingCtaAttributes as `attr:${K}`]?: PricingCtaAttributes[K] } & { [K in keyof PricingCta & keyof PricingCtaAttributes as `prop:${K}`]?: PricingCta[K] };
        "pulumi-api-doc-filterable-nav": Omit<PulumiApiDocFilterableNav, keyof PulumiApiDocFilterableNavAttributes> & { [K in keyof PulumiApiDocFilterableNav & keyof PulumiApiDocFilterableNavAttributes]?: PulumiApiDocFilterableNav[K] } & { [K in keyof PulumiApiDocFilterableNav & keyof PulumiApiDocFilterableNavAttributes as `attr:${K}`]?: PulumiApiDocFilterableNavAttributes[K] } & { [K in keyof PulumiApiDocFilterableNav & keyof PulumiApiDocFilterableNavAttributes as `prop:${K}`]?: PulumiApiDocFilterableNav[K] };
        "pulumi-api-doc-nav-node": Omit<PulumiApiDocNavNode, keyof PulumiApiDocNavNodeAttributes> & { [K in keyof PulumiApiDocNavNode & keyof PulumiApiDocNavNodeAttributes]?: PulumiApiDocNavNode[K] } & { [K in keyof PulumiApiDocNavNode & keyof PulumiApiDocNavNodeAttributes as `attr:${K}`]?: PulumiApiDocNavNodeAttributes[K] } & { [K in keyof PulumiApiDocNavNode & keyof PulumiApiDocNavNodeAttributes as `prop:${K}`]?: PulumiApiDocNavNode[K] };
        "pulumi-api-doc-nav-tree": Omit<PulumiApiDocNavTree, keyof PulumiApiDocNavTreeAttributes> & { [K in keyof PulumiApiDocNavTree & keyof PulumiApiDocNavTreeAttributes]?: PulumiApiDocNavTree[K] } & { [K in keyof PulumiApiDocNavTree & keyof PulumiApiDocNavTreeAttributes as `attr:${K}`]?: PulumiApiDocNavTreeAttributes[K] } & { [K in keyof PulumiApiDocNavTree & keyof PulumiApiDocNavTreeAttributes as `prop:${K}`]?: PulumiApiDocNavTree[K] };
        "pulumi-audio": Omit<PulumiAudio, keyof PulumiAudioAttributes> & { [K in keyof PulumiAudio & keyof PulumiAudioAttributes]?: PulumiAudio[K] } & { [K in keyof PulumiAudio & keyof PulumiAudioAttributes as `attr:${K}`]?: PulumiAudioAttributes[K] } & { [K in keyof PulumiAudio & keyof PulumiAudioAttributes as `prop:${K}`]?: PulumiAudio[K] };
        "pulumi-banner": Omit<PulumiBanner, keyof PulumiBannerAttributes> & { [K in keyof PulumiBanner & keyof PulumiBannerAttributes]?: PulumiBanner[K] } & { [K in keyof PulumiBanner & keyof PulumiBannerAttributes as `attr:${K}`]?: PulumiBannerAttributes[K] } & { [K in keyof PulumiBanner & keyof PulumiBannerAttributes as `prop:${K}`]?: PulumiBanner[K] };
        "pulumi-choosable": Omit<PulumiChoosable, keyof PulumiChoosableAttributes> & { [K in keyof PulumiChoosable & keyof PulumiChoosableAttributes]?: PulumiChoosable[K] } & { [K in keyof PulumiChoosable & keyof PulumiChoosableAttributes as `attr:${K}`]?: PulumiChoosableAttributes[K] } & { [K in keyof PulumiChoosable & keyof PulumiChoosableAttributes as `prop:${K}`]?: PulumiChoosable[K] };
        "pulumi-chooser": Omit<PulumiChooser, keyof PulumiChooserAttributes> & { [K in keyof PulumiChooser & keyof PulumiChooserAttributes]?: PulumiChooser[K] } & { [K in keyof PulumiChooser & keyof PulumiChooserAttributes as `attr:${K}`]?: PulumiChooserAttributes[K] } & { [K in keyof PulumiChooser & keyof PulumiChooserAttributes as `prop:${K}`]?: PulumiChooser[K] };
        "pulumi-contact-us-form": Omit<PulumiContactUsForm, keyof PulumiContactUsFormAttributes> & { [K in keyof PulumiContactUsForm & keyof PulumiContactUsFormAttributes]?: PulumiContactUsForm[K] } & { [K in keyof PulumiContactUsForm & keyof PulumiContactUsFormAttributes as `attr:${K}`]?: PulumiContactUsFormAttributes[K] } & { [K in keyof PulumiContactUsForm & keyof PulumiContactUsFormAttributes as `prop:${K}`]?: PulumiContactUsForm[K] };
        "pulumi-convert": Omit<PulumiConvert, keyof PulumiConvertAttributes> & { [K in keyof PulumiConvert & keyof PulumiConvertAttributes]?: PulumiConvert[K] } & { [K in keyof PulumiConvert & keyof PulumiConvertAttributes as `attr:${K}`]?: PulumiConvertAttributes[K] } & { [K in keyof PulumiConvert & keyof PulumiConvertAttributes as `prop:${K}`]?: PulumiConvert[K] };
        "pulumi-date-countdown": Omit<PulumiDateCountdown, keyof PulumiDateCountdownAttributes> & { [K in keyof PulumiDateCountdown & keyof PulumiDateCountdownAttributes]?: PulumiDateCountdown[K] } & { [K in keyof PulumiDateCountdown & keyof PulumiDateCountdownAttributes as `attr:${K}`]?: PulumiDateCountdownAttributes[K] } & { [K in keyof PulumiDateCountdown & keyof PulumiDateCountdownAttributes as `prop:${K}`]?: PulumiDateCountdown[K] };
        "pulumi-date-countdown-circles": Omit<PulumiDateCountdownCircles, keyof PulumiDateCountdownCirclesAttributes> & { [K in keyof PulumiDateCountdownCircles & keyof PulumiDateCountdownCirclesAttributes]?: PulumiDateCountdownCircles[K] } & { [K in keyof PulumiDateCountdownCircles & keyof PulumiDateCountdownCirclesAttributes as `attr:${K}`]?: PulumiDateCountdownCirclesAttributes[K] } & { [K in keyof PulumiDateCountdownCircles & keyof PulumiDateCountdownCirclesAttributes as `prop:${K}`]?: PulumiDateCountdownCircles[K] };
        "pulumi-datetime": Omit<PulumiDatetime, keyof PulumiDatetimeAttributes> & { [K in keyof PulumiDatetime & keyof PulumiDatetimeAttributes]?: PulumiDatetime[K] } & { [K in keyof PulumiDatetime & keyof PulumiDatetimeAttributes as `attr:${K}`]?: PulumiDatetimeAttributes[K] } & { [K in keyof PulumiDatetime & keyof PulumiDatetimeAttributes as `prop:${K}`]?: PulumiDatetime[K] };
        "pulumi-developer-quotes": Omit<PulumiDeveloperQuotes, keyof PulumiDeveloperQuotesAttributes> & { [K in keyof PulumiDeveloperQuotes & keyof PulumiDeveloperQuotesAttributes]?: PulumiDeveloperQuotes[K] } & { [K in keyof PulumiDeveloperQuotes & keyof PulumiDeveloperQuotesAttributes as `attr:${K}`]?: PulumiDeveloperQuotesAttributes[K] } & { [K in keyof PulumiDeveloperQuotes & keyof PulumiDeveloperQuotesAttributes as `prop:${K}`]?: PulumiDeveloperQuotes[K] };
        "pulumi-docs-nav": Omit<PulumiDocsNav, keyof PulumiDocsNavAttributes> & { [K in keyof PulumiDocsNav & keyof PulumiDocsNavAttributes]?: PulumiDocsNav[K] } & { [K in keyof PulumiDocsNav & keyof PulumiDocsNavAttributes as `attr:${K}`]?: PulumiDocsNavAttributes[K] } & { [K in keyof PulumiDocsNav & keyof PulumiDocsNavAttributes as `prop:${K}`]?: PulumiDocsNav[K] };
        "pulumi-example": PulumiExample;
        "pulumi-examples": PulumiExamples;
        "pulumi-filter-select": PulumiFilterSelect;
        "pulumi-filter-select-option": Omit<PulumiFilterSelectOption, keyof PulumiFilterSelectOptionAttributes> & { [K in keyof PulumiFilterSelectOption & keyof PulumiFilterSelectOptionAttributes]?: PulumiFilterSelectOption[K] } & { [K in keyof PulumiFilterSelectOption & keyof PulumiFilterSelectOptionAttributes as `attr:${K}`]?: PulumiFilterSelectOptionAttributes[K] } & { [K in keyof PulumiFilterSelectOption & keyof PulumiFilterSelectOptionAttributes as `prop:${K}`]?: PulumiFilterSelectOption[K] };
        "pulumi-filter-select-option-group": Omit<PulumiFilterSelectOptionGroup, keyof PulumiFilterSelectOptionGroupAttributes> & { [K in keyof PulumiFilterSelectOptionGroup & keyof PulumiFilterSelectOptionGroupAttributes]?: PulumiFilterSelectOptionGroup[K] } & { [K in keyof PulumiFilterSelectOptionGroup & keyof PulumiFilterSelectOptionGroupAttributes as `attr:${K}`]?: PulumiFilterSelectOptionGroupAttributes[K] } & { [K in keyof PulumiFilterSelectOptionGroup & keyof PulumiFilterSelectOptionGroupAttributes as `prop:${K}`]?: PulumiFilterSelectOptionGroup[K] };
        "pulumi-greenhouse-jobs-list": PulumiGreenhouseJobsList;
        "pulumi-hubspot-form": Omit<PulumiHubspotForm, keyof PulumiHubspotFormAttributes> & { [K in keyof PulumiHubspotForm & keyof PulumiHubspotFormAttributes]?: PulumiHubspotForm[K] } & { [K in keyof PulumiHubspotForm & keyof PulumiHubspotFormAttributes as `attr:${K}`]?: PulumiHubspotFormAttributes[K] } & { [K in keyof PulumiHubspotForm & keyof PulumiHubspotFormAttributes as `prop:${K}`]?: PulumiHubspotForm[K] };
        "pulumi-install": Omit<PulumiInstall, keyof PulumiInstallAttributes> & { [K in keyof PulumiInstall & keyof PulumiInstallAttributes]?: PulumiInstall[K] } & { [K in keyof PulumiInstall & keyof PulumiInstallAttributes as `attr:${K}`]?: PulumiInstallAttributes[K] } & { [K in keyof PulumiInstall & keyof PulumiInstallAttributes as `prop:${K}`]?: PulumiInstall[K] };
        "pulumi-llm-menu": Omit<PulumiLlmMenu, keyof PulumiLlmMenuAttributes> & { [K in keyof PulumiLlmMenu & keyof PulumiLlmMenuAttributes]?: PulumiLlmMenu[K] } & { [K in keyof PulumiLlmMenu & keyof PulumiLlmMenuAttributes as `attr:${K}`]?: PulumiLlmMenuAttributes[K] } & { [K in keyof PulumiLlmMenu & keyof PulumiLlmMenuAttributes as `prop:${K}`]?: PulumiLlmMenu[K] };
        "pulumi-multi-select-form": Omit<PulumiMultiSelectForm, keyof PulumiMultiSelectFormAttributes> & { [K in keyof PulumiMultiSelectForm & keyof PulumiMultiSelectFormAttributes]?: PulumiMultiSelectForm[K] } & { [K in keyof PulumiMultiSelectForm & keyof PulumiMultiSelectFormAttributes as `attr:${K}`]?: PulumiMultiSelectFormAttributes[K] } & { [K in keyof PulumiMultiSelectForm & keyof PulumiMultiSelectFormAttributes as `prop:${K}`]?: PulumiMultiSelectForm[K] };
        "pulumi-pricing-calculator": PulumiPricingCalculator;
        "pulumi-registry-list-search": PulumiRegistryListSearch;
        "pulumi-resource-links": Omit<PulumiResourceLinks, keyof PulumiResourceLinksAttributes> & { [K in keyof PulumiResourceLinks & keyof PulumiResourceLinksAttributes]?: PulumiResourceLinks[K] } & { [K in keyof PulumiResourceLinks & keyof PulumiResourceLinksAttributes as `attr:${K}`]?: PulumiResourceLinksAttributes[K] } & { [K in keyof PulumiResourceLinks & keyof PulumiResourceLinksAttributes as `prop:${K}`]?: PulumiResourceLinks[K] };
        "pulumi-root": PulumiRoot;
        "pulumi-slot-machine": Omit<PulumiSlotMachine, keyof PulumiSlotMachineAttributes> & { [K in keyof PulumiSlotMachine & keyof PulumiSlotMachineAttributes]?: PulumiSlotMachine[K] } & { [K in keyof PulumiSlotMachine & keyof PulumiSlotMachineAttributes as `attr:${K}`]?: PulumiSlotMachineAttributes[K] } & { [K in keyof PulumiSlotMachine & keyof PulumiSlotMachineAttributes as `prop:${K}`]?: PulumiSlotMachine[K] };
        "pulumi-swipeable": PulumiSwipeable;
        "pulumi-swiper": Omit<PulumiSwiper, keyof PulumiSwiperAttributes> & { [K in keyof PulumiSwiper & keyof PulumiSwiperAttributes]?: PulumiSwiper[K] } & { [K in keyof PulumiSwiper & keyof PulumiSwiperAttributes as `attr:${K}`]?: PulumiSwiperAttributes[K] } & { [K in keyof PulumiSwiper & keyof PulumiSwiperAttributes as `prop:${K}`]?: PulumiSwiper[K] };
        "pulumi-tab": Omit<PulumiTab, keyof PulumiTabAttributes> & { [K in keyof PulumiTab & keyof PulumiTabAttributes]?: PulumiTab[K] } & { [K in keyof PulumiTab & keyof PulumiTabAttributes as `attr:${K}`]?: PulumiTabAttributes[K] } & { [K in keyof PulumiTab & keyof PulumiTabAttributes as `prop:${K}`]?: PulumiTab[K] };
        "pulumi-tabs": PulumiTabs;
        "pulumi-tertiary-nav": Omit<PulumiTertiaryNav, keyof PulumiTertiaryNavAttributes> & { [K in keyof PulumiTertiaryNav & keyof PulumiTertiaryNavAttributes]?: PulumiTertiaryNav[K] } & { [K in keyof PulumiTertiaryNav & keyof PulumiTertiaryNavAttributes as `attr:${K}`]?: PulumiTertiaryNavAttributes[K] } & { [K in keyof PulumiTertiaryNav & keyof PulumiTertiaryNavAttributes as `prop:${K}`]?: PulumiTertiaryNav[K] };
        "pulumi-tooltip": PulumiTooltip;
        "pulumi-top-button": PulumiTopButton;
        "pulumi-user-toggle": Omit<PulumiUserToggle, keyof PulumiUserToggleAttributes> & { [K in keyof PulumiUserToggle & keyof PulumiUserToggleAttributes]?: PulumiUserToggle[K] } & { [K in keyof PulumiUserToggle & keyof PulumiUserToggleAttributes as `attr:${K}`]?: PulumiUserToggleAttributes[K] } & { [K in keyof PulumiUserToggle & keyof PulumiUserToggleAttributes as `prop:${K}`]?: PulumiUserToggle[K] };
        "pulumi-value-calculator": PulumiValueCalculator;
        "pulumi-webinar-form-select": Omit<PulumiWebinarFormSelect, keyof PulumiWebinarFormSelectAttributes> & { [K in keyof PulumiWebinarFormSelect & keyof PulumiWebinarFormSelectAttributes]?: PulumiWebinarFormSelect[K] } & { [K in keyof PulumiWebinarFormSelect & keyof PulumiWebinarFormSelectAttributes as `attr:${K}`]?: PulumiWebinarFormSelectAttributes[K] } & { [K in keyof PulumiWebinarFormSelect & keyof PulumiWebinarFormSelectAttributes as `prop:${K}`]?: PulumiWebinarFormSelect[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "copilot-sidebar": LocalJSX.IntrinsicElements["copilot-sidebar"] & JSXBase.HTMLAttributes<HTMLCopilotSidebarElement>;
            "event-session-registration-modal": LocalJSX.IntrinsicElements["event-session-registration-modal"] & JSXBase.HTMLAttributes<HTMLEventSessionRegistrationModalElement>;
            "header-cta": LocalJSX.IntrinsicElements["header-cta"] & JSXBase.HTMLAttributes<HTMLHeaderCtaElement>;
            "home-slots": LocalJSX.IntrinsicElements["home-slots"] & JSXBase.HTMLAttributes<HTMLHomeSlotsElement>;
            "pricing-cta": LocalJSX.IntrinsicElements["pricing-cta"] & JSXBase.HTMLAttributes<HTMLPricingCtaElement>;
            "pulumi-api-doc-filterable-nav": LocalJSX.IntrinsicElements["pulumi-api-doc-filterable-nav"] & JSXBase.HTMLAttributes<HTMLPulumiApiDocFilterableNavElement>;
            "pulumi-api-doc-nav-node": LocalJSX.IntrinsicElements["pulumi-api-doc-nav-node"] & JSXBase.HTMLAttributes<HTMLPulumiApiDocNavNodeElement>;
            "pulumi-api-doc-nav-tree": LocalJSX.IntrinsicElements["pulumi-api-doc-nav-tree"] & JSXBase.HTMLAttributes<HTMLPulumiApiDocNavTreeElement>;
            "pulumi-audio": LocalJSX.IntrinsicElements["pulumi-audio"] & JSXBase.HTMLAttributes<HTMLPulumiAudioElement>;
            "pulumi-banner": LocalJSX.IntrinsicElements["pulumi-banner"] & JSXBase.HTMLAttributes<HTMLPulumiBannerElement>;
            /**
             * The Choosable component is useful for showing or hiding information based on the
             * currently selected ChooserType and value. For example, a component defined as:
             *     <pulumi-choosable type="language" value="typescript">
             *         I <3 TypeScript.
             *     </pulumi-choosable>
             * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
             * selected language choice is TypeScript.
             */
            "pulumi-choosable": LocalJSX.IntrinsicElements["pulumi-choosable"] & JSXBase.HTMLAttributes<HTMLPulumiChoosableElement>;
            /**
             * The Chooser component renders a set of selectable tabs based on the type and options
             * properties provided. For example, this definition:
             *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
             * ...would render three tabs. Clicking a tab dispatches an action that sets the
             * associated value on the store, allowing any pulumi-choosable component on the page to
             * be shown or hidden automatically.
             * Alternatively, you can provide one or more pulumi-choosable components as children of
             * this component, which will have the effect of treating them as tabbed content,
             * irrespective of what may or may not be set on the global store. For example:
             *     <pulumi-chooser type="language" value="typescript,javascript">
             *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
             *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
             *     </pulumi-chooser>
             */
            "pulumi-chooser": LocalJSX.IntrinsicElements["pulumi-chooser"] & JSXBase.HTMLAttributes<HTMLPulumiChooserElement>;
            "pulumi-contact-us-form": LocalJSX.IntrinsicElements["pulumi-contact-us-form"] & JSXBase.HTMLAttributes<HTMLPulumiContactUsFormElement>;
            "pulumi-convert": LocalJSX.IntrinsicElements["pulumi-convert"] & JSXBase.HTMLAttributes<HTMLPulumiConvertElement>;
            "pulumi-date-countdown": LocalJSX.IntrinsicElements["pulumi-date-countdown"] & JSXBase.HTMLAttributes<HTMLPulumiDateCountdownElement>;
            "pulumi-date-countdown-circles": LocalJSX.IntrinsicElements["pulumi-date-countdown-circles"] & JSXBase.HTMLAttributes<HTMLPulumiDateCountdownCirclesElement>;
            "pulumi-datetime": LocalJSX.IntrinsicElements["pulumi-datetime"] & JSXBase.HTMLAttributes<HTMLPulumiDatetimeElement>;
            "pulumi-developer-quotes": LocalJSX.IntrinsicElements["pulumi-developer-quotes"] & JSXBase.HTMLAttributes<HTMLPulumiDeveloperQuotesElement>;
            "pulumi-docs-nav": LocalJSX.IntrinsicElements["pulumi-docs-nav"] & JSXBase.HTMLAttributes<HTMLPulumiDocsNavElement>;
            "pulumi-example": LocalJSX.IntrinsicElements["pulumi-example"] & JSXBase.HTMLAttributes<HTMLPulumiExampleElement>;
            "pulumi-examples": LocalJSX.IntrinsicElements["pulumi-examples"] & JSXBase.HTMLAttributes<HTMLPulumiExamplesElement>;
            "pulumi-filter-select": LocalJSX.IntrinsicElements["pulumi-filter-select"] & JSXBase.HTMLAttributes<HTMLPulumiFilterSelectElement>;
            "pulumi-filter-select-option": LocalJSX.IntrinsicElements["pulumi-filter-select-option"] & JSXBase.HTMLAttributes<HTMLPulumiFilterSelectOptionElement>;
            "pulumi-filter-select-option-group": LocalJSX.IntrinsicElements["pulumi-filter-select-option-group"] & JSXBase.HTMLAttributes<HTMLPulumiFilterSelectOptionGroupElement>;
            "pulumi-greenhouse-jobs-list": LocalJSX.IntrinsicElements["pulumi-greenhouse-jobs-list"] & JSXBase.HTMLAttributes<HTMLPulumiGreenhouseJobsListElement>;
            "pulumi-hubspot-form": LocalJSX.IntrinsicElements["pulumi-hubspot-form"] & JSXBase.HTMLAttributes<HTMLPulumiHubspotFormElement>;
            "pulumi-install": LocalJSX.IntrinsicElements["pulumi-install"] & JSXBase.HTMLAttributes<HTMLPulumiInstallElement>;
            "pulumi-llm-menu": LocalJSX.IntrinsicElements["pulumi-llm-menu"] & JSXBase.HTMLAttributes<HTMLPulumiLlmMenuElement>;
            "pulumi-multi-select-form": LocalJSX.IntrinsicElements["pulumi-multi-select-form"] & JSXBase.HTMLAttributes<HTMLPulumiMultiSelectFormElement>;
            "pulumi-pricing-calculator": LocalJSX.IntrinsicElements["pulumi-pricing-calculator"] & JSXBase.HTMLAttributes<HTMLPulumiPricingCalculatorElement>;
            "pulumi-registry-list-search": LocalJSX.IntrinsicElements["pulumi-registry-list-search"] & JSXBase.HTMLAttributes<HTMLPulumiRegistryListSearchElement>;
            "pulumi-resource-links": LocalJSX.IntrinsicElements["pulumi-resource-links"] & JSXBase.HTMLAttributes<HTMLPulumiResourceLinksElement>;
            "pulumi-root": LocalJSX.IntrinsicElements["pulumi-root"] & JSXBase.HTMLAttributes<HTMLPulumiRootElement>;
            "pulumi-slot-machine": LocalJSX.IntrinsicElements["pulumi-slot-machine"] & JSXBase.HTMLAttributes<HTMLPulumiSlotMachineElement>;
            "pulumi-swipeable": LocalJSX.IntrinsicElements["pulumi-swipeable"] & JSXBase.HTMLAttributes<HTMLPulumiSwipeableElement>;
            "pulumi-swiper": LocalJSX.IntrinsicElements["pulumi-swiper"] & JSXBase.HTMLAttributes<HTMLPulumiSwiperElement>;
            "pulumi-tab": LocalJSX.IntrinsicElements["pulumi-tab"] & JSXBase.HTMLAttributes<HTMLPulumiTabElement>;
            "pulumi-tabs": LocalJSX.IntrinsicElements["pulumi-tabs"] & JSXBase.HTMLAttributes<HTMLPulumiTabsElement>;
            "pulumi-tertiary-nav": LocalJSX.IntrinsicElements["pulumi-tertiary-nav"] & JSXBase.HTMLAttributes<HTMLPulumiTertiaryNavElement>;
            /**
             * The ToolTip component shows a tooltip bubble above another element when you hover over
             * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
             * show in the bubble.
             * Usage:
             * <pulumi-tooltip>
             *     <i class="fas fa-question-circle"></i>
             *     <span slot="content">
             *         You hovered over (or tapped on) the thing!
             *     </span>
             * </pulumi-tooltip>
             */
            "pulumi-tooltip": LocalJSX.IntrinsicElements["pulumi-tooltip"] & JSXBase.HTMLAttributes<HTMLPulumiTooltipElement>;
            "pulumi-top-button": LocalJSX.IntrinsicElements["pulumi-top-button"] & JSXBase.HTMLAttributes<HTMLPulumiTopButtonElement>;
            "pulumi-user-toggle": LocalJSX.IntrinsicElements["pulumi-user-toggle"] & JSXBase.HTMLAttributes<HTMLPulumiUserToggleElement>;
            "pulumi-value-calculator": LocalJSX.IntrinsicElements["pulumi-value-calculator"] & JSXBase.HTMLAttributes<HTMLPulumiValueCalculatorElement>;
            "pulumi-webinar-form-select": LocalJSX.IntrinsicElements["pulumi-webinar-form-select"] & JSXBase.HTMLAttributes<HTMLPulumiWebinarFormSelectElement>;
        }
    }
}
