config:
  aws:region: us-west-2
  www.pulumi.com:addSecurityHeaders: "true"
  www.pulumi.com:certificateArn: "arn:aws:acm:us-east-1:571684982431:certificate/35773c92-83c6-4196-9912-2c823883d252"
  www.pulumi.com:doEdgeRedirects: "true"
  www.pulumi.com:makeFallbackBucket: "false"
  www.pulumi.com:pathToOriginBucketMetadata: ../origin-bucket-metadata.json
  www.pulumi.com:websiteDomain: www.pulumi-test.io
  www.pulumi.com:websiteLogsBucketName: pulumi-test-io-website-logs
  www.pulumi.com:hostedZone: www.pulumi-test.io
  www.pulumi.com:setRootRecord: true
  www.pulumi.com:testingFlow: true
