name: Hugo Build
on: [pull_request]
jobs:
  hugoBuild:
    name: Run Hugo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          yarn install
          yarn run lint-markdown
      - name: Build Stencil components
        working-directory: components
        env:
          NODE_ENV: production
        run: |
          yarn install
          yarn run build
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.55.4'
          extended: true
      - name: Build
        run: hugo --minify -v
        env:
          NODE_ENV: production
