name: Build site with Hugo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # Run every day at 12:00AM.
    - cron:  '0 0 * * *'
jobs:
  buildSite:
    env:
      GOPATH: ${{ github.workspace }}
    name: Install deps and build site
    runs-on: ubuntu-latest
    # Max timeout before this job is killed.
    # This is also useful when a workflow execution is paused by
    # the Turnstyle action (see below) when another workflow is currently
    # executing. It prevents a workflow from waiting indefinitely.
    timeout-minutes: 30
    steps:
      # Turnstyle is used to prevent multiple push jobs from
      # running at the same time.
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.55.4'
          extended: true

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Install assume-role
        run: go get -u github.com/remind101/assume-role

      - name: Add GOBIN to PATH
        run: echo "::add-path::$(go env GOPATH)/bin"

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1

      - run: make ci_${GITHUB_EVENT_NAME}
        if: github.event_name != 'schedule'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Run scheduled job
        run: make ci_cron
        if: github.event_name == 'schedule'
