name: Build site with Hugo
on: [pull_request, push]
jobs:
  setupDeps:
    name: Setup dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.55.4'
          extended: true
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Install assume-role
        run: go get -u github.com/remind101/assume-role
      - name: Install latest Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com/ | bash -s
          export PATH=$PATH:$HOME/.pulumi/bin
      - run: make travis_${GITHUB_EVENT_NAME}
        
      
      