permissions: write-all # Equivalent to default permissions + id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-docs
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

name: Pulumi CLI release dispatcher
on:
  repository_dispatch:
    types:
      - pulumi-cli

jobs:
  dispatch-pulumi-cli-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v2
      - name: Dispatch Pulumi CLI docs workflow
        env:
          GH_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
        run: |
          gh workflow run pulumi-cli-docs.yml \
            --repo ${{ github.repository }} \
            --ref master \
            -f version=${{ github.event.client_payload.ref }}
  dispatch-pulumi-sdk-typescript-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v2
      - name: Dispatch Pulumi SDK TypeScript docs workflow
        env:
          GH_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
        run: |
          gh workflow run pulumi-sdk-typescript-docs.yml \
            --repo ${{ github.repository }} \
            --ref master \
            -f version=${{ github.event.client_payload.ref }}
  dispatch-pulumi-sdk-python-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v2
      - name: Dispatch Pulumi SDK Python docs workflow
        env:
          GH_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
        run: |
          gh workflow run pulumi-sdk-python-docs.yml \
            --repo ${{ github.repository }} \
            --ref master \
            -f version=${{ github.event.client_payload.ref }}
