name: Unlock testing workflow
on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC = 2 AM ET / 11 PM PT
  workflow_dispatch: null
permissions:
  actions: write
jobs:
  unlock:
    name: Re-enable testing workflow
    runs-on: ubuntu-latest
    steps:
      - name: Enable testing-build-and-deploy workflow
        run: gh workflow enable testing-build-and-deploy.yml --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
