name: "Scheduled jobs: Update tutorials"
on:
  schedule:
    - cron:  '0 15 * * *'
  workflow_dispatch:
jobs:
  merge:
    name: Update tutorials
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}

      - name: Run mktutorial
        run: |
          ./scripts/mktutorial.sh

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: tutorials/refresh
          author: Pulumi Bot <bot@pulumi.com>
          committer: Pulumi Bot <bot@pulumi.com>
          title: Update tutorials
          labels: "automation/merge"
          commit-message: Update tutorials
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          body: |
            Regenerate all tutorials based on the latest available content at https://github.com/pulumi/examples.
  notify:
    if: failure()
    name: Send slack notification
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: docs-ops
          SLACK_COLOR: "#F54242"
          SLACK_MESSAGE: "update tutorials failure in pulumi/docs repo :meow_sad:"
          SLACK_USERNAME: docsbot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON: https://www.pulumi.com/logos/brand/avatar-on-white.png
